language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - travis_retry pip install -r requirements.txt "jinja2>=2.7" msgpack-python pyyaml pytest>=3.3.2 pytest-cov arrow
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then travis_retry pip install pint coveralls ply; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then py.test tests/ --ignore=tests/contrib --cov=odin ; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then py.test tests/ --cov=odin ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coveralls; fi
