from dataqualityhdfs.core.granularity.granularitytimeinterval import GranularityTimeInterval
from dataqualityhdfs.core.granularity.granularity import Granularity
from dataqualityhdfs.core.granularity.granularitytemporal import GranularityTemporal