- project:
    check:
      jobs:
        - ironic-lib-tempest-partition-agent_ipmitool
        - ironic-lib-tempest-partition-pxe_ipmitool
        - ironic-lib-tempest-wholedisk-agent_ipmitool
        - ironic-lib-tempest-wholedisk-pxe_ipmitool
    gate:
      jobs:
        - ironic-lib-tempest-partition-agent_ipmitool
        - ironic-lib-tempest-partition-pxe_ipmitool
        - ironic-lib-tempest-wholedisk-agent_ipmitool
        - ironic-lib-tempest-wholedisk-pxe_ipmitool
