
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-04-05T17:59:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "02274851c40fed7f39d3be105c381a967310f2ad",
 "version": "0.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
