
from operator import attrgetter
import pyangbind.lib.xpathhelper as xpathhelper
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
class license(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module brocade-system-capabilities - based on the path /capabilities/license. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_path_helper', '_yang_name', '_rest_name', '_extmethods', '__eula_display','__dpod_display','__slot_display',)

  _yang_name = 'license'
  _rest_name = 'license'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    path_helper_ = kwargs.pop("path_helper", None)
    if path_helper_ is False:
      self._path_helper = False
    elif path_helper_ is not None and isinstance(path_helper_, xpathhelper.YANGPathHelper):
      self._path_helper = path_helper_
    elif hasattr(self, "_parent"):
      path_helper_ = getattr(self._parent, "_path_helper", False)
      self._path_helper = path_helper_
    else:
      self._path_helper = False

    extmethods = kwargs.pop("extmethods", None)
    if extmethods is False:
      self._extmethods = False
    elif extmethods is not None and isinstance(extmethods, dict):
      self._extmethods = extmethods
    elif hasattr(self, "_parent"):
      extmethods = getattr(self._parent, "_extmethods", None)
      self._extmethods = extmethods
    else:
      self._extmethods = False
    self.__eula_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="eula_display", rest_name="eula_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)
    self.__dpod_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="dpod_display", rest_name="dpod_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)
    self.__slot_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="slot_display", rest_name="slot_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'capabilities', u'license']

  def _rest_path(self):
    if hasattr(self, "_parent"):
      if self._rest_name:
        return self._parent._rest_path()+[self._rest_name]
      else:
        return self._parent._rest_path()
    else:
      return [u'capabilities', u'license']

  def _get_eula_display(self):
    """
    Getter method for eula_display, mapped from YANG variable /capabilities/license/eula_display (boolean)
    """
    return self.__eula_display
      
  def _set_eula_display(self, v, load=False):
    """
    Setter method for eula_display, mapped from YANG variable /capabilities/license/eula_display (boolean)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_eula_display is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_eula_display() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGBool, is_leaf=True, yang_name="eula_display", rest_name="eula_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """eula_display must be of a type compatible with boolean""",
          'defined-type': "boolean",
          'generated-type': """YANGDynClass(base=YANGBool, is_leaf=True, yang_name="eula_display", rest_name="eula_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)""",
        })

    self.__eula_display = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_eula_display(self):
    self.__eula_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="eula_display", rest_name="eula_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)


  def _get_dpod_display(self):
    """
    Getter method for dpod_display, mapped from YANG variable /capabilities/license/dpod_display (boolean)
    """
    return self.__dpod_display
      
  def _set_dpod_display(self, v, load=False):
    """
    Setter method for dpod_display, mapped from YANG variable /capabilities/license/dpod_display (boolean)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_dpod_display is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_dpod_display() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGBool, is_leaf=True, yang_name="dpod_display", rest_name="dpod_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """dpod_display must be of a type compatible with boolean""",
          'defined-type': "boolean",
          'generated-type': """YANGDynClass(base=YANGBool, is_leaf=True, yang_name="dpod_display", rest_name="dpod_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)""",
        })

    self.__dpod_display = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_dpod_display(self):
    self.__dpod_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="dpod_display", rest_name="dpod_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)


  def _get_slot_display(self):
    """
    Getter method for slot_display, mapped from YANG variable /capabilities/license/slot_display (boolean)
    """
    return self.__slot_display
      
  def _set_slot_display(self, v, load=False):
    """
    Setter method for slot_display, mapped from YANG variable /capabilities/license/slot_display (boolean)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_slot_display is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_slot_display() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGBool, is_leaf=True, yang_name="slot_display", rest_name="slot_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """slot_display must be of a type compatible with boolean""",
          'defined-type': "boolean",
          'generated-type': """YANGDynClass(base=YANGBool, is_leaf=True, yang_name="slot_display", rest_name="slot_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)""",
        })

    self.__slot_display = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_slot_display(self):
    self.__slot_display = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="slot_display", rest_name="slot_display", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-system-capabilities', defining_module='brocade-system-capabilities', yang_type='boolean', is_config=False)

  eula_display = __builtin__.property(_get_eula_display)
  dpod_display = __builtin__.property(_get_dpod_display)
  slot_display = __builtin__.property(_get_slot_display)


  _pyangbind_elements = {'eula_display': eula_display, 'dpod_display': dpod_display, 'slot_display': slot_display, }


