__version__ = '0.0.4'
__description__ = 'A gui for interacting with the a hierarchical scene graph'
__author__ = 'Paxton Gerrish'
__email__ = 'creaturecastlabs@gmail.com'
__url__ = 'https://github.com/Paxtongerrish/creaturecast_scenegraph.git'
