# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_list_selector_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(855, 814)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LBL_MESSAGE = QtWidgets.QLabel(Dialog)
        self.LBL_MESSAGE.setObjectName("LBL_MESSAGE")
        self.verticalLayout_2.addWidget(self.LBL_MESSAGE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GRP_LEFT = QtWidgets.QGroupBox(Dialog)
        self.GRP_LEFT.setObjectName("GRP_LEFT")
        self.gridLayout = QtWidgets.QGridLayout(self.GRP_LEFT)
        self.gridLayout.setObjectName("gridLayout")
        self.TVW_LEFT = QtWidgets.QTreeWidget(self.GRP_LEFT)
        self.TVW_LEFT.setObjectName("TVW_LEFT")
        self.TVW_LEFT.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.TVW_LEFT, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.GRP_LEFT)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.BTN_REMOVE_ONE = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_REMOVE_ONE.sizePolicy().hasHeightForWidth())
        self.BTN_REMOVE_ONE.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Desktop/110964-basic-application/svg/arrowhead-thin-outline-to-the-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE_ONE.setIcon(icon)
        self.BTN_REMOVE_ONE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE_ONE.setObjectName("BTN_REMOVE_ONE")
        self.verticalLayout.addWidget(self.BTN_REMOVE_ONE)
        self.BTN_REMOVE_ALL = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_REMOVE_ALL.sizePolicy().hasHeightForWidth())
        self.BTN_REMOVE_ALL.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Desktop/110964-basic-application/svg/arrowheads-of-thin-outline-to-the-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REMOVE_ALL.setIcon(icon1)
        self.BTN_REMOVE_ALL.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REMOVE_ALL.setObjectName("BTN_REMOVE_ALL")
        self.verticalLayout.addWidget(self.BTN_REMOVE_ALL)
        self.BTN_ADD = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ADD.sizePolicy().hasHeightForWidth())
        self.BTN_ADD.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Desktop/110964-basic-application/svg/arrow-point-to-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ADD.setIcon(icon2)
        self.BTN_ADD.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_ADD.setObjectName("BTN_ADD")
        self.verticalLayout.addWidget(self.BTN_ADD)
        self.BTN_ADD_ALL = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ADD_ALL.sizePolicy().hasHeightForWidth())
        self.BTN_ADD_ALL.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Desktop/110964-basic-application/svg/right-thin-arrowheads.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ADD_ALL.setIcon(icon3)
        self.BTN_ADD_ALL.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_ADD_ALL.setObjectName("BTN_ADD_ALL")
        self.verticalLayout.addWidget(self.BTN_ADD_ALL)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.GRP_RIGHT = QtWidgets.QGroupBox(Dialog)
        self.GRP_RIGHT.setObjectName("GRP_RIGHT")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GRP_RIGHT)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TVW_RIGHT = QtWidgets.QTreeWidget(self.GRP_RIGHT)
        self.TVW_RIGHT.setObjectName("TVW_RIGHT")
        self.TVW_RIGHT.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.TVW_RIGHT, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.GRP_RIGHT)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.BTNBOX_MAIN = QtWidgets.QDialogButtonBox(Dialog)
        self.BTNBOX_MAIN.setOrientation(QtCore.Qt.Horizontal)
        self.BTNBOX_MAIN.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.BTNBOX_MAIN.setObjectName("BTNBOX_MAIN")
        self.verticalLayout_2.addWidget(self.BTNBOX_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LBL_MESSAGE.setText(_translate("Dialog", "TextLabel"))
        self.GRP_LEFT.setTitle(_translate("Dialog", "Right"))
        self.BTN_REMOVE_ONE.setText(_translate("Dialog", "Remove"))
        self.BTN_REMOVE_ALL.setText(_translate("Dialog", "Remove all"))
        self.BTN_ADD.setText(_translate("Dialog", "Add"))
        self.BTN_ADD_ALL.setText(_translate("Dialog", "Add all"))
        self.GRP_RIGHT.setTitle(_translate("Dialog", "Left"))

