- name: "[setting oracle allowed vars]"
  set_fact:
    allowed_role_vars:
        - debug
        - oracle_java_set_as_default
        - oracle_java_state
        - oracle_java_version
        - oracle_java_version_string

- name: "[setting role vars]"
  set_fact: {"{{ item }}": "{{ role_package['vars'][item] }}"}
  when: "role_package['vars'].get(item, False)"
  with_items:
      - "{{ allowed_role_vars }}"

- name: "starting oracle-java install"
  include_role:
    name: "ansiblebit.oracle-java"
