sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - docker pull mysql
  - docker run --name mysqldb -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=password mysql

install: "pip install -r requirements.txt"

script:
  - python -m unittest etlstat/database/test/testMySQL.py
  - python -m unittest etlstat/extractor/test/testExtractor.py
  - python -m unittest etlstat/extractor/test/testPcaxis.py
  - python -m unittest etlstat/security/test/testPassword.py

after_script:
  - docker rm -f mysqldb