__version__ = '0.1.4'
__title__ = 'omdata'
__description__ = 'OpenMaker survey data schema editor.'
__url__ = 'http://github.com/bulentozel/omdata'
__author__ = 'Bulent Ozel'
__author_email__ = 'bulent.ozel@gmail.com'
__license__ = 'Apache2'
__copyright__ = 'Copyright 2018 Bulent Ozel'
