[tool.poetry]
name = "poetry"
version = "0.7.0b4"
description = "Python dependency management and packaging made easy."
authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]
license = "MIT"

readme = "README.md"

homepage = "https://poetry.eustace.io/"
repository = "https://github.com/sdispater/poet"
documentation = "https://poetry.eustace.io/docs"

keywords = ["packaging", "dependency", "poetry"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

# Requirements
[tool.poetry.dependencies]
python = "^3.4"
cleo = "^0.6"
requests = "^2.18"
toml = "^0.9"
cachy = "^0.1.1"
pip-tools = "^1.11"
requests-toolbelt = "^0.8.0"
jsonschema = "^2.6"
pyrsistent = "^0.14.2"
pyparsing = "^2.2"

# zipfile36 is needed for Python 3.4 and 3.5
zipfile36 = { version = "^0.1", python = ">=3.4 <3.6" }

# The typing module is not in the stdlib in Python 3.4
typing = { version = "^3.6", python = "~3.4" }

[tool.poetry.dev-dependencies]
pytest = "^3.4"
pytest-cov = "^2.5"
mkdocs = "^0.17.3"
pymdown-extensions = "^4.9"
pygments = "^2.2"


[tool.poetry.scripts]
poetry = "poetry.console:main"
