---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'lxc/pre_main.yml') }}"

- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ lxc_distribution_packages[ansible_distribution] }}'

- name: Check available LXC package version
  shell: lxc-create --version
  register: lxc_register_package_version
  changed_when: False

# Configure LXC support when correct version is installed
- include: configure_lxc.yml
  when: (lxc_register_package_version is defined and
         lxc_register_package_version.stdout is version_compare('1.0','>='))

# Install backported Linux kernel on Debian Wheezy
- include: install_kernel_from_backports.yml
  when: (ansible_distribution == 'Debian' and
         ansible_distribution_release == 'wheezy')

# Manage LXC containers via Ansible when correct kernel is installed
- include: manage_containers.yml
  when: (lxc_containers is defined and lxc_containers) and
        ansible_kernel is version_compare('3.10','>')

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save LXC local facts
  template:
    src: 'etc/ansible/facts.d/lxc.fact.j2'
    dest: '/etc/ansible/facts.d/lxc.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: lxc__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: lxc__register_facts is changed

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'lxc/post_main.yml') }}"
