language: python
sudo: false

git:
  submodules: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3

addons:
  apt:
    packages:
    - ttf-dejavu

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p ~/.fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O /Library/Fonts/Ahem.ttf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget "http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2" -O /tmp/dejavu.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf /tmp/dejavu.tar.bz2 -C /tmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /tmp/dejavu*/ttf/*.ttf /Library/Fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 cairo pango gdk-pixbuf libffi; fi

install:
  # First line needed because of https://github.com/pypa/setuptools/pull/1089
  # Can be removed as soon as setuptools-36.2.0 is not the default version anymore on Travis with Python 3.6
  - pip$PYTHON_VERSION install --upgrade setuptools
  - pip$PYTHON_VERSION install --upgrade -e.[test]

script:
  - python$PYTHON_VERSION setup.py test
