sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION="Django>=1.8,<1.9 djangorestframework<3.7"
  - DJANGO_VERSION="Django>=1.9,<1.10 djangorestframework<3.7"
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<1.12"
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install -r test_requirements.txt
  - pip install -q $DJANGO_VERSION
script: python -Wall $VIRTUAL_ENV/bin/coverage run webmap/tests/runtests.py
before_script:
  - django-admin --version
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
addons:
  postgresql: "9.6"
  apt:
     packages:
        - postgresql-9.6-postgis-2.3
after_script:
  - coveralls
matrix:
   exclude:
      - python: "2.7"
        env: DJANGO_VERSION="Django>=2.0,<2.1"
      - python: "2.7"
        env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
      - python: "3.4"
        env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
