- name: "[calculating target]"
  set_fact:
    copy_target: "{{ freckle_local_parent_path }}/{{ freckle_item_metadata.local_name }}"
  when: "not freckle_item_metadata.checkout_skip"

- name: "[check if rsync is available]"
  required_executable_facts:
    executables_to_check:
      - rsync
  when: "not freckle_item_metadata.checkout_skip"

- name: "[create freckle parent folder]"
  file:
    state: directory
    recurse: true
    path: "{{ freckle_local_parent_path }}"
  become: "{{ freckle_item_metadata.checkout_become }}"
  when: "not freckle_item_metadata.checkout_skip"

- name: "copying '{{ freckle_item_metadata.remote_url }}' to '{{ copy_target }}'"
  copy:
    src: "{{ freckle_item_metadata.remote_url }}/"
    dest: "{{ copy_target }}"
  become: "{{ freckle_item_metadata.checkout_become }}"
  when: "not freckle_item_metadata.checkout_skip and 'rsync' in executables_missing"

- name: "rsyncing '{{ freckle_item_metadata.remote_url }}' to '{{ copy_target }}'"
  synchronize:
    src: "{{ freckle_item_metadata.remote_url }}/"
    dest: "{{ copy_target }}"
  become: "{{ freckle_item_metadata.checkout_become }}"
  when: "not freckle_item_metadata.checkout_skip and 'rsync' not in executables_missing"

- name: "deleting blueprint source"
  local_action:
    module: file
    path: "{{ freckle_item_metadata.remote_url }}"
    state: absent
  # become: true
  when: freckle_item_metadata.source_delete
