# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_view_options_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(944, 781)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -208, 907, 950))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LBL_VISJS_WARNING_2 = QtWidgets.QLabel(self.frame)
        self.LBL_VISJS_WARNING_2.setObjectName("LBL_VISJS_WARNING_2")
        self.verticalLayout_4.addWidget(self.LBL_VISJS_WARNING_2)
        self.RAD_TREE_ASK = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_ASK.setObjectName("RAD_TREE_ASK")
        self.verticalLayout_4.addWidget(self.RAD_TREE_ASK)
        self.RAD_TREE_SYSTEM = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_SYSTEM.setObjectName("RAD_TREE_SYSTEM")
        self.verticalLayout_4.addWidget(self.RAD_TREE_SYSTEM)
        self.RAD_TREE_INBUILT = QtWidgets.QRadioButton(self.frame)
        self.RAD_TREE_INBUILT.setObjectName("RAD_TREE_INBUILT")
        self.verticalLayout_4.addWidget(self.RAD_TREE_INBUILT)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LBL_VISJS_WARNING_3 = QtWidgets.QLabel(self.frame_2)
        self.LBL_VISJS_WARNING_3.setObjectName("LBL_VISJS_WARNING_3")
        self.verticalLayout_5.addWidget(self.LBL_VISJS_WARNING_3)
        self.RAD_STARTUP_MESSAGE = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_MESSAGE.setObjectName("RAD_STARTUP_MESSAGE")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_MESSAGE)
        self.RAD_STARTUP_WORKFLOW = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_WORKFLOW.setObjectName("RAD_STARTUP_WORKFLOW")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_WORKFLOW)
        self.RAD_STARTUP_SAMPLES = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_SAMPLES.setObjectName("RAD_STARTUP_SAMPLES")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_SAMPLES)
        self.RAD_STARTUP_NOTHING = QtWidgets.QRadioButton(self.frame_2)
        self.RAD_STARTUP_NOTHING.setObjectName("RAD_STARTUP_NOTHING")
        self.verticalLayout_5.addWidget(self.RAD_STARTUP_NOTHING)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LBL_VISJS_WARNING_4 = QtWidgets.QLabel(self.frame_3)
        self.LBL_VISJS_WARNING_4.setObjectName("LBL_VISJS_WARNING_4")
        self.verticalLayout_6.addWidget(self.LBL_VISJS_WARNING_4)
        self.RAD_WIN_MDI = QtWidgets.QRadioButton(self.frame_3)
        self.RAD_WIN_MDI.setObjectName("RAD_WIN_MDI")
        self.verticalLayout_6.addWidget(self.RAD_WIN_MDI)
        self.RAD_WIN_TDI = QtWidgets.QRadioButton(self.frame_3)
        self.RAD_WIN_TDI.setObjectName("RAD_WIN_TDI")
        self.verticalLayout_6.addWidget(self.RAD_WIN_TDI)
        self.RAD_WIN_NORMAL = QtWidgets.QRadioButton(self.frame_3)
        self.RAD_WIN_NORMAL.setObjectName("RAD_WIN_NORMAL")
        self.verticalLayout_6.addWidget(self.RAD_WIN_NORMAL)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LBL_VISJS_WARNING_7 = QtWidgets.QLabel(self.frame_4)
        self.LBL_VISJS_WARNING_7.setObjectName("LBL_VISJS_WARNING_7")
        self.verticalLayout_7.addWidget(self.LBL_VISJS_WARNING_7)
        self.RAD_JS_VIS = QtWidgets.QRadioButton(self.frame_4)
        self.RAD_JS_VIS.setObjectName("RAD_JS_VIS")
        self.verticalLayout_7.addWidget(self.RAD_JS_VIS)
        self.RAD_JS_CY = QtWidgets.QRadioButton(self.frame_4)
        self.RAD_JS_CY.setObjectName("RAD_JS_CY")
        self.verticalLayout_7.addWidget(self.RAD_JS_CY)
        self.RAD_JS_NONE = QtWidgets.QRadioButton(self.frame_4)
        self.RAD_JS_NONE.setObjectName("RAD_JS_NONE")
        self.verticalLayout_7.addWidget(self.RAD_JS_NONE)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.LBL_VISJS_WARNING_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LBL_VISJS_WARNING_6.setObjectName("LBL_VISJS_WARNING_6")
        self.verticalLayout_2.addWidget(self.LBL_VISJS_WARNING_6)
        self.CHKTOOL_FILE = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CHKTOOL_FILE.setObjectName("CHKTOOL_FILE")
        self.verticalLayout_2.addWidget(self.CHKTOOL_FILE)
        self.CHKTOOL_VIS = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CHKTOOL_VIS.setObjectName("CHKTOOL_VIS")
        self.verticalLayout_2.addWidget(self.CHKTOOL_VIS)
        self.CHKTOOL_WORKFLOW = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CHKTOOL_WORKFLOW.setObjectName("CHKTOOL_WORKFLOW")
        self.verticalLayout_2.addWidget(self.CHKTOOL_WORKFLOW)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.BTN_CLEAR_RECENT = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_CLEAR_RECENT.sizePolicy().hasHeightForWidth())
        self.BTN_CLEAR_RECENT.setSizePolicy(sizePolicy)
        self.BTN_CLEAR_RECENT.setMinimumSize(QtCore.QSize(192, 0))
        self.BTN_CLEAR_RECENT.setMaximumSize(QtCore.QSize(192, 16777215))
        self.BTN_CLEAR_RECENT.setAutoDefault(False)
        self.BTN_CLEAR_RECENT.setObjectName("BTN_CLEAR_RECENT")
        self.verticalLayout_2.addWidget(self.BTN_CLEAR_RECENT)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.LBL_VISJS_WARNING_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LBL_VISJS_WARNING_5.setObjectName("LBL_VISJS_WARNING_5")
        self.verticalLayout_2.addWidget(self.LBL_VISJS_WARNING_5)
        self.BTN_INTERMAKE = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.BTN_INTERMAKE.setMinimumSize(QtCore.QSize(192, 0))
        self.BTN_INTERMAKE.setMaximumSize(QtCore.QSize(192, 16777215))
        self.BTN_INTERMAKE.setAutoDefault(False)
        self.BTN_INTERMAKE.setObjectName("BTN_INTERMAKE")
        self.verticalLayout_2.addWidget(self.BTN_INTERMAKE)
        self.BTN_INTERMAKE_EXP = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.BTN_INTERMAKE_EXP.setMinimumSize(QtCore.QSize(192, 0))
        self.BTN_INTERMAKE_EXP.setMaximumSize(QtCore.QSize(192, 16777215))
        self.BTN_INTERMAKE_EXP.setAutoDefault(False)
        self.BTN_INTERMAKE_EXP.setObjectName("BTN_INTERMAKE_EXP")
        self.verticalLayout_2.addWidget(self.BTN_INTERMAKE_EXP)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(141, 241, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 20, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 2)
        self.horizontalFrame_5 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_5.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_5.setSizePolicy(sizePolicy)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RAD_XSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_YES.setObjectName("RAD_XSNAP_YES")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_YES)
        self.RAD_XSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_NO.setObjectName("RAD_XSNAP_NO")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_NO)
        self.RAD_XSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_IND.setObjectName("RAD_XSNAP_IND")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_5, 16, 1, 1, 1)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_4.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_4.setSizePolicy(sizePolicy)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RAD_POS_YES = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_POS_YES.setSizePolicy(sizePolicy)
        self.RAD_POS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_YES.setObjectName("RAD_POS_YES")
        self.horizontalLayout_5.addWidget(self.RAD_POS_YES)
        self.RAD_POS_NO = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_POS_NO.setSizePolicy(sizePolicy)
        self.RAD_POS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_NO.setObjectName("RAD_POS_NO")
        self.horizontalLayout_5.addWidget(self.RAD_POS_NO)
        self.RAD_POS_IND = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_POS_IND.setSizePolicy(sizePolicy)
        self.RAD_POS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_IND.setObjectName("RAD_POS_IND")
        self.horizontalLayout_5.addWidget(self.RAD_POS_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_4, 8, 1, 1, 1)
        self.horizontalFrame_9 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_9.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_9.setSizePolicy(sizePolicy)
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RAD_COMPONENTS_YES = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_YES.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_YES.setObjectName("RAD_COMPONENTS_YES")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_YES)
        self.RAD_COMPONENTS_NO = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_NO.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_NO.setObjectName("RAD_COMPONENTS_NO")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_NO)
        self.RAD_COMPONENTS_IND = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_IND.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_IND.setObjectName("RAD_COMPONENTS_IND")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_9, 10, 1, 1, 1)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RAD_MOVE_YES = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_YES.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_YES.setSizePolicy(sizePolicy)
        self.RAD_MOVE_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_YES.setObjectName("RAD_MOVE_YES")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_YES)
        self.RAD_MOVE_NO = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_NO.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_NO.setSizePolicy(sizePolicy)
        self.RAD_MOVE_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_NO.setObjectName("RAD_MOVE_NO")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_NO)
        self.RAD_MOVE_IND = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_IND.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_IND.setSizePolicy(sizePolicy)
        self.RAD_MOVE_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_IND.setObjectName("RAD_MOVE_IND")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_3, 14, 1, 1, 1)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAD_PIANO_YES = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_YES.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_YES.setSizePolicy(sizePolicy)
        self.RAD_PIANO_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_YES.setObjectName("RAD_PIANO_YES")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_YES)
        self.RAD_PIANO_NO = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_NO.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_NO.setSizePolicy(sizePolicy)
        self.RAD_PIANO_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_NO.setObjectName("RAD_PIANO_NO")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_NO)
        self.RAD_PIANO_IND = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_IND.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_IND.setSizePolicy(sizePolicy)
        self.RAD_PIANO_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_IND.setObjectName("RAD_PIANO_IND")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_2, 6, 1, 1, 1)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_6.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_6.setSizePolicy(sizePolicy)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RAD_YSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_YES.setObjectName("RAD_YSNAP_YES")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_YES)
        self.RAD_YSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_NO.setObjectName("RAD_YSNAP_NO")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_NO)
        self.RAD_YSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_IND.setObjectName("RAD_YSNAP_IND")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_6, 18, 1, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAD_NAME_YES = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_YES.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_YES.setSizePolicy(sizePolicy)
        self.RAD_NAME_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_YES.setObjectName("RAD_NAME_YES")
        self.horizontalLayout.addWidget(self.RAD_NAME_YES)
        self.RAD_NAME_NO = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_NO.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_NO.setSizePolicy(sizePolicy)
        self.RAD_NAME_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_NO.setObjectName("RAD_NAME_NO")
        self.horizontalLayout.addWidget(self.RAD_NAME_NO)
        self.RAD_NAME_IND = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_IND.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_IND.setSizePolicy(sizePolicy)
        self.RAD_NAME_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_IND.setObjectName("RAD_NAME_IND")
        self.horizontalLayout.addWidget(self.RAD_NAME_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 16, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 14, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 12, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 18, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 13, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_16.setText(_translate("Dialog", "These settings affect all Groot sessions."))
        self.label_16.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_11.setText(_translate("Dialog", "Graph browser"))
        self.label_11.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_2.setText(_translate("Dialog", "Choose how to view the graphs.\n"
"Normally Groot will ask you, but you can select a default preference here."))
        self.LBL_VISJS_WARNING_2.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_TREE_ASK.setText(_translate("Dialog", "Ask every time"))
        self.RAD_TREE_SYSTEM.setText(_translate("Dialog", "Only use the system browser"))
        self.RAD_TREE_INBUILT.setText(_translate("Dialog", "Only use the inbult browser"))
        self.label_9.setText(_translate("Dialog", "Startup"))
        self.label_9.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_3.setText(_translate("Dialog", "Choose what to display when Groot starts."))
        self.LBL_VISJS_WARNING_3.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_STARTUP_MESSAGE.setText(_translate("Dialog", "Show the startup message"))
        self.RAD_STARTUP_WORKFLOW.setText(_translate("Dialog", "Show the workflow"))
        self.RAD_STARTUP_SAMPLES.setText(_translate("Dialog", "Show the open file dialogue"))
        self.RAD_STARTUP_NOTHING.setText(_translate("Dialog", "Don\'t show anything"))
        self.label_12.setText(_translate("Dialog", "View"))
        self.label_12.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_4.setText(_translate("Dialog", "Select how Groot\'s windows are displayed.\n"
"Note that MDI and TDI may not be supported or work correctly on all platforms.\n"
"Changes to this setting will only take effect when the GUI is restarted."))
        self.LBL_VISJS_WARNING_4.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_WIN_MDI.setToolTip(_translate("Dialog", "Multiple Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_WIN_MDI.setText(_translate("Dialog", "MDI"))
        self.RAD_WIN_TDI.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_WIN_TDI.setText(_translate("Dialog", "TDI"))
        self.RAD_WIN_NORMAL.setToolTip(_translate("Dialog", "Display the windows normally."))
        self.RAD_WIN_NORMAL.setText(_translate("Dialog", "Basic"))
        self.label_15.setText(_translate("Dialog", "Javascript"))
        self.label_15.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_7.setText(_translate("Dialog", "Select the default Javascript library used to display graphs.\n"
"If you don\'t select one then Groot\'s static display will be used (not recommended)."))
        self.LBL_VISJS_WARNING_7.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_JS_VIS.setToolTip(_translate("Dialog", "Multiple Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_VIS.setText(_translate("Dialog", "Vis.js"))
        self.RAD_JS_CY.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_CY.setText(_translate("Dialog", "Cytoscape.js"))
        self.RAD_JS_NONE.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_NONE.setText(_translate("Dialog", "None"))
        self.label_13.setText(_translate("Dialog", "Toolbar"))
        self.label_13.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_6.setText(_translate("Dialog", "Select what toolbars are displayed."))
        self.LBL_VISJS_WARNING_6.setProperty("style", _translate("Dialog", "helpbox"))
        self.CHKTOOL_FILE.setText(_translate("Dialog", "File"))
        self.CHKTOOL_VIS.setText(_translate("Dialog", "Visualisers"))
        self.CHKTOOL_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.label_4.setText(_translate("Dialog", "Micellaneous"))
        self.label_4.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_CLEAR_RECENT.setText(_translate("Dialog", "Clear recent files history"))
        self.label_26.setText(_translate("Dialog", "Intermake"))
        self.label_26.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_5.setText(_translate("Dialog", "Intermake handles algorithm call and response.\n"
"Settings such as whether to keep windows open after running an algorithm can be found here.\n"
"You can also explore the Groot model through Intermake."))
        self.LBL_VISJS_WARNING_5.setProperty("style", _translate("Dialog", "helpbox"))
        self.BTN_INTERMAKE.setText(_translate("Dialog", "Intermake configuration"))
        self.BTN_INTERMAKE_EXP.setText(_translate("Dialog", "Intermake explorer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Groot"))
        self.label_24.setText(_translate("Dialog", "Select what\'s visible on the diagrams."))
        self.label_24.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_XSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_XSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_XSNAP_IND.setText(_translate("Dialog", "Without ᴄᴛʀʟ"))
        self.RAD_POS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_POS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_POS_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_COMPONENTS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_COMPONENTS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_COMPONENTS_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_MOVE_YES.setText(_translate("Dialog", "Always"))
        self.RAD_MOVE_NO.setText(_translate("Dialog", "Never"))
        self.RAD_MOVE_IND.setText(_translate("Dialog", "Double click toggles"))
        self.RAD_PIANO_YES.setText(_translate("Dialog", "Always"))
        self.RAD_PIANO_NO.setText(_translate("Dialog", "Never"))
        self.RAD_PIANO_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_YSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_YSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_YSNAP_IND.setText(_translate("Dialog", "Without ᴀʟᴛ"))
        self.RAD_NAME_YES.setText(_translate("Dialog", "Always"))
        self.RAD_NAME_NO.setText(_translate("Dialog", "Never"))
        self.RAD_NAME_IND.setText(_translate("Dialog", "When selected"))
        self.label_2.setText(_translate("Dialog", "Piano rolls"))
        self.label_6.setText(_translate("Dialog", "X-snap"))
        self.label_3.setText(_translate("Dialog", "Movement"))
        self.label_5.setText(_translate("Dialog", "Positions"))
        self.label_17.setText(_translate("Dialog", "Lego Diagram Editing"))
        self.label_17.setProperty("style", _translate("Dialog", "heading"))
        self.label.setText(_translate("Dialog", "Gene names"))
        self.label_7.setText(_translate("Dialog", "Y-snap"))
        self.label_10.setText(_translate("Dialog", "Components"))
        self.label_19.setText(_translate("Dialog", "These settings only affect the current model."))
        self.label_19.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_14.setText(_translate("Dialog", "Lego Diagram Viewing"))
        self.label_14.setProperty("style", _translate("Dialog", "heading"))
        self.label_25.setText(_translate("Dialog", "Select how you\'ll edit your diagrams."))
        self.label_25.setProperty("style", _translate("Dialog", "helpbox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Lego"))


