
from operator import attrgetter
import pyangbind.lib.xpathhelper as xpathhelper
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
import __builtin__
class filter_list(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module brocade-bgp-operational - based on the path /bgp-state/neighbor/evpn/filter-list. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_pybind_generated_by', '_path_helper', '_yang_name', '_rest_name', '_extmethods', '__in_','__out','__in_name','__out_name',)

  _yang_name = 'filter-list'
  _rest_name = 'filter-list'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    path_helper_ = kwargs.pop("path_helper", None)
    if path_helper_ is False:
      self._path_helper = False
    elif path_helper_ is not None and isinstance(path_helper_, xpathhelper.YANGPathHelper):
      self._path_helper = path_helper_
    elif hasattr(self, "_parent"):
      path_helper_ = getattr(self._parent, "_path_helper", False)
      self._path_helper = path_helper_
    else:
      self._path_helper = False

    extmethods = kwargs.pop("extmethods", None)
    if extmethods is False:
      self._extmethods = False
    elif extmethods is not None and isinstance(extmethods, dict):
      self._extmethods = extmethods
    elif hasattr(self, "_parent"):
      extmethods = getattr(self._parent, "_extmethods", None)
      self._extmethods = extmethods
    else:
      self._extmethods = False
    self.__in_ = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="in", rest_name="in", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)
    self.__out_name = YANGDynClass(base=unicode, is_leaf=True, yang_name="out-name", rest_name="out-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)
    self.__in_name = YANGDynClass(base=unicode, is_leaf=True, yang_name="in-name", rest_name="in-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)
    self.__out = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="out", rest_name="out", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'bgp-state', u'neighbor', u'evpn', u'filter-list']

  def _rest_path(self):
    if hasattr(self, "_parent"):
      if self._rest_name:
        return self._parent._rest_path()+[self._rest_name]
      else:
        return self._parent._rest_path()
    else:
      return [u'bgp-state', u'neighbor', u'evpn', u'filter-list']

  def _get_in_(self):
    """
    Getter method for in_, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/in (boolean)

    YANG Description: Direction in
    """
    return self.__in_
      
  def _set_in_(self, v, load=False):
    """
    Setter method for in_, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/in (boolean)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_in_ is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_in_() directly.

    YANG Description: Direction in
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGBool, is_leaf=True, yang_name="in", rest_name="in", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """in_ must be of a type compatible with boolean""",
          'defined-type': "boolean",
          'generated-type': """YANGDynClass(base=YANGBool, is_leaf=True, yang_name="in", rest_name="in", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)""",
        })

    self.__in_ = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_in_(self):
    self.__in_ = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="in", rest_name="in", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)


  def _get_out(self):
    """
    Getter method for out, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/out (boolean)

    YANG Description: Direction out
    """
    return self.__out
      
  def _set_out(self, v, load=False):
    """
    Setter method for out, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/out (boolean)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_out is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_out() directly.

    YANG Description: Direction out
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGBool, is_leaf=True, yang_name="out", rest_name="out", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """out must be of a type compatible with boolean""",
          'defined-type': "boolean",
          'generated-type': """YANGDynClass(base=YANGBool, is_leaf=True, yang_name="out", rest_name="out", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)""",
        })

    self.__out = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_out(self):
    self.__out = YANGDynClass(base=YANGBool, is_leaf=True, yang_name="out", rest_name="out", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='boolean', is_config=False)


  def _get_in_name(self):
    """
    Getter method for in_name, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/in_name (string)

    YANG Description: Access list name
    """
    return self.__in_name
      
  def _set_in_name(self, v, load=False):
    """
    Setter method for in_name, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/in_name (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_in_name is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_in_name() directly.

    YANG Description: Access list name
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="in-name", rest_name="in-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """in_name must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="in-name", rest_name="in-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)""",
        })

    self.__in_name = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_in_name(self):
    self.__in_name = YANGDynClass(base=unicode, is_leaf=True, yang_name="in-name", rest_name="in-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)


  def _get_out_name(self):
    """
    Getter method for out_name, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/out_name (string)

    YANG Description: Access list name
    """
    return self.__out_name
      
  def _set_out_name(self, v, load=False):
    """
    Setter method for out_name, mapped from YANG variable /bgp_state/neighbor/evpn/filter_list/out_name (string)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_out_name is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_out_name() directly.

    YANG Description: Access list name
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=unicode, is_leaf=True, yang_name="out-name", rest_name="out-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """out_name must be of a type compatible with string""",
          'defined-type': "string",
          'generated-type': """YANGDynClass(base=unicode, is_leaf=True, yang_name="out-name", rest_name="out-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)""",
        })

    self.__out_name = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_out_name(self):
    self.__out_name = YANGDynClass(base=unicode, is_leaf=True, yang_name="out-name", rest_name="out-name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='urn:brocade.com:mgmt:brocade-bgp-operational', defining_module='brocade-bgp-operational', yang_type='string', is_config=False)

  in_ = __builtin__.property(_get_in_)
  out = __builtin__.property(_get_out)
  in_name = __builtin__.property(_get_in_name)
  out_name = __builtin__.property(_get_out_name)


  _pyangbind_elements = {'in_': in_, 'out': out, 'in_name': in_name, 'out_name': out_name, }


