# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plover/gui_qt/config_serial_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialWidget(object):
    def setupUi(self, SerialWidget):
        SerialWidget.setObjectName("SerialWidget")
        SerialWidget.resize(314, 431)
        self.gridLayout = QtWidgets.QGridLayout(SerialWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(SerialWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.port = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setEditable(True)
        self.port.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.port.setObjectName("port")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port)
        self.scan = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan.sizePolicy().hasHeightForWidth())
        self.scan.setSizePolicy(sizePolicy)
        self.scan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scan.setObjectName("scan")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scan)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.baudrate = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrate.sizePolicy().hasHeightForWidth())
        self.baudrate.setSizePolicy(sizePolicy)
        self.baudrate.setObjectName("baudrate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.bytesize = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bytesize.sizePolicy().hasHeightForWidth())
        self.bytesize.setSizePolicy(sizePolicy)
        self.bytesize.setObjectName("bytesize")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bytesize)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.stopbits = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbits.sizePolicy().hasHeightForWidth())
        self.stopbits.setSizePolicy(sizePolicy)
        self.stopbits.setObjectName("stopbits")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stopbits)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.parity = QtWidgets.QComboBox(self.groupBox_2)
        self.parity.setObjectName("parity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parity)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeout = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.timeout.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeout.sizePolicy().hasHeightForWidth())
        self.timeout.setSizePolicy(sizePolicy)
        self.timeout.setSingleStep(0.1)
        self.timeout.setObjectName("timeout")
        self.horizontalLayout.addWidget(self.timeout)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.use_timeout = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_timeout.sizePolicy().hasHeightForWidth())
        self.use_timeout.setSizePolicy(sizePolicy)
        self.use_timeout.setObjectName("use_timeout")
        self.verticalLayout_2.addWidget(self.use_timeout)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xonxoff = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xonxoff.sizePolicy().hasHeightForWidth())
        self.xonxoff.setSizePolicy(sizePolicy)
        self.xonxoff.setObjectName("xonxoff")
        self.verticalLayout.addWidget(self.xonxoff)
        self.rtscts = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rtscts.sizePolicy().hasHeightForWidth())
        self.rtscts.setSizePolicy(sizePolicy)
        self.rtscts.setObjectName("rtscts")
        self.verticalLayout.addWidget(self.rtscts)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(SerialWidget)
        self.scan.clicked.connect(SerialWidget.on_scan)
        self.baudrate.activated['QString'].connect(SerialWidget.on_baudrate_changed)
        self.bytesize.activated['QString'].connect(SerialWidget.on_bytesize_changed)
        self.parity.activated['QString'].connect(SerialWidget.on_parity_changed)
        self.port.editTextChanged['QString'].connect(SerialWidget.on_port_changed)
        self.stopbits.activated['QString'].connect(SerialWidget.on_stopbits_changed)
        self.use_timeout.clicked['bool'].connect(SerialWidget.on_use_timeout_changed)
        self.xonxoff.clicked['bool'].connect(SerialWidget.on_xonxoff_changed)
        self.rtscts.clicked['bool'].connect(SerialWidget.on_rtscts_changed)
        self.timeout.valueChanged['double'].connect(SerialWidget.on_timeout_changed)
        QtCore.QMetaObject.connectSlotsByName(SerialWidget)

    def retranslateUi(self, SerialWidget):

        SerialWidget.setWindowTitle(_("Form"))
        self.groupBox.setTitle(_("Connection"))
        self.label.setText(_("Port"))
        self.scan.setText(_("Scan"))
        self.label_2.setText(_("Baudrate"))
        self.groupBox_2.setTitle(_("Data format"))
        self.label_3.setText(_("Data bits"))
        self.label_4.setText(_("Stop bits"))
        self.label_5.setText(_("Parity"))
        self.groupBox_3.setTitle(_("Timeout"))
        self.label_6.setText(_("seconds"))
        self.use_timeout.setText(_("Use timeout"))
        self.groupBox_4.setTitle(_("Flow control"))
        self.xonxoff.setText(_("Xon/Xoff"))
        self.rtscts.setText(_("RTS/CTS"))

