__version__ = '0.0.14'
__description__ = 'A gui for downloading launching and managing creaturecast tools'
__author__ = 'Paxton Gerrish'
__email__ = 'creaturecastlabs@gmail.com'
__url__ = 'https://github.com/Paxtongerrish/creaturecast_designer.git'
