version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\\pip\\Cache'

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

  matrix:
    # PYTHON 2.7
    - PYTHON: "C:\\Miniconda27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "111"

    - PYTHON: "C:\\Miniconda27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "111"

    # PYTHON 3.5
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "142"

#    - PYTHON: "C:\\Miniconda35-x64"
#      PYTHON_VERSION: "3.5"
#      PYTHON_ARCH: "64"
#      CONDA_PY: "35"
#      CONDA_NPY: "142"

    # PYTHON 3.6
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"
      CONDA_NPY: "142"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_NPY: "142"


install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  # Build and test the package. This appears(?) to sporadically fail due to a
  # bug in conda-build on 32 bit python.
  # https://github.com/conda/conda-build/issues/152
  #
  # Note also that our setup.py script, which is called by conda-build, writes
  # a __conda_version__.txt file, so the version number on the binary package
  # is set dynamically. This unfortunately mean that conda build --output
  # doesn't really work.
  #
    - "%CMD_IN_ENV% conda install --yes --quiet cython pandas mock"

  # Build the compiled extension and run the project tests
    - "%CMD_IN_ENV% python setup.py build_ext --inplace"
    - "%CMD_IN_ENV% python -c \"import bcolz; bcolz.test(heavy=True)\""
