language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
#  - "2.6"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install psycopg2 oursql python-coveralls codecov
  - travis_retry pip install -e . -r requirements.txt
  - pip uninstall -y Kotti
  - python setup.py develop
  - python setup.py dev
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script:
  - py.test -rw --runslow --tb=native --cov=kotti --cov-report=term-missing
after_success:
  - coveralls
  - codecov
notifications:
  irc: "irc.freenode.org#kotti"
  email: false
