stages:
  - test
  - deploy

test-3.6-VS2017:
  stage:
    test
  tags:
    - VS2017
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - set Path=%Path%;C:\Program Files\Python36;C:\Program Files\Python36\Scripts;
    - virtualenv --clear -p "C:\Program Files\Python36\python.exe" .
    - call .\Scripts\activate
    - pip install -e .
    - cd tests
    - python -m unittest discover

test-3.5-linux:
  stage:
    test
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - pip install -e .
    - cd tests
    - python -m unittest discover

test-3.5-macos:
  stage:
    test
  tags:
    - Apple
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - pip install -e .
    - cd tests
    - python -m unittest discover

test-2.7-linux:
  stage:
    test
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python2.7 .
    - source bin/activate
    - pip install -e .
    - cd tests
    - python -m unittest discover

test-2.7-macos:
  stage:
    test
  tags:
    - Apple
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python2.7 .
    - source bin/activate
    - pip install -e .
    - cd tests
    - python -m unittest discover

deploy-wheel:
  stage:
    deploy
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - python setup.py bdist_wheel --universal
    - mkdir -p release
    - cp dist/*.whl release/
  artifacts:
    paths:
      - release/*.whl

deploy-documentation:
  stage:
    deploy
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - mkdir -p documentation
    - cd docs
    - make html
    - cp -r build/html/* ../documentation
  artifacts:
    paths:
      - documentation/
