from setuptools import setup
setup(
    author='Kieran O\'Leary',
    author_email='kieran.o.leary@gmail.com',
    description='IFIscripts',
    scripts=[
        'sipcreator.py',
        'ififuncs.py',
        'copyit.py',
        'masscopy.py',
        'accession.py',
        'batchaccession.py',
        'concat.py',
        'makeffv1.py',
        'loopline.py',
        'makepbcore.py',
        'manifest.py',
        'validate.py',
        'Objects.py',
        'makedfxml.py',
        'walk_to_dfxml.py',
        'bitc.py',
        'prores.py',
        'dcpfixity.py',
        'dcpaccess.py',
        'deletefiles.py',
        'rearrange.py',
        'durationcheck.py',
        'ffv1mkvvalidate.py',
        'loopline_repackage.py',
        'seq2ffv1.py',
        'makeuuid.py',
        'masscopy.py',
        'packagecheck.py',
        'testfiles.py'
    ],
    license='MIT',
    install_requires=[
       'lxml',
       'bagit'
    ],
    name='ifiscripts',
    version='0.7'
)
