# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot/frontends/gui/forms/designer/frm_big_text_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1021, 655)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FRA_TOOLBAR = QtWidgets.QFrame(Dialog)
        self.FRA_TOOLBAR.setObjectName("FRA_TOOLBAR")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FRA_TOOLBAR)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridGroupBox = QtWidgets.QGroupBox(self.FRA_TOOLBAR)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.CHK_MISCELLANEOUS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_MISCELLANEOUS.setObjectName("CHK_MISCELLANEOUS")
        self.gridLayout.addWidget(self.CHK_MISCELLANEOUS, 0, 2, 1, 1)
        self.CHK_GRAPHS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_GRAPHS.setObjectName("CHK_GRAPHS")
        self.gridLayout.addWidget(self.CHK_GRAPHS, 1, 1, 1, 1)
        self.CHK_FASTA = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_FASTA.setObjectName("CHK_FASTA")
        self.gridLayout.addWidget(self.CHK_FASTA, 0, 0, 1, 1)
        self.CHK_DATA = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_DATA.setObjectName("CHK_DATA")
        self.gridLayout.addWidget(self.CHK_DATA, 0, 1, 1, 1)
        self.CHK_ALIGNMENTS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_ALIGNMENTS.setObjectName("CHK_ALIGNMENTS")
        self.gridLayout.addWidget(self.CHK_ALIGNMENTS, 1, 0, 1, 1)
        self.CHK_COLOURS = QtWidgets.QCheckBox(self.gridGroupBox)
        self.CHK_COLOURS.setObjectName("CHK_COLOURS")
        self.gridLayout.addWidget(self.CHK_COLOURS, 1, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridGroupBox)
        self.line = QtWidgets.QFrame(self.FRA_TOOLBAR)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.BTN_REFRESH = QtWidgets.QToolButton(self.FRA_TOOLBAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_REFRESH.sizePolicy().hasHeightForWidth())
        self.BTN_REFRESH.setSizePolicy(sizePolicy)
        self.BTN_REFRESH.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_REFRESH.setMaximumSize(QtCore.QSize(64, 64))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/groot/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REFRESH.setIcon(icon)
        self.BTN_REFRESH.setIconSize(QtCore.QSize(32, 32))
        self.BTN_REFRESH.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_3.addWidget(self.BTN_REFRESH)
        self.BTN_SAVE = QtWidgets.QToolButton(self.FRA_TOOLBAR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SAVE.sizePolicy().hasHeightForWidth())
        self.BTN_SAVE.setSizePolicy(sizePolicy)
        self.BTN_SAVE.setMinimumSize(QtCore.QSize(64, 64))
        self.BTN_SAVE.setMaximumSize(QtCore.QSize(64, 64))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SAVE.setIcon(icon1)
        self.BTN_SAVE.setIconSize(QtCore.QSize(32, 32))
        self.BTN_SAVE.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTN_SAVE.setObjectName("BTN_SAVE")
        self.horizontalLayout_3.addWidget(self.BTN_SAVE)
        self.verticalLayout.addWidget(self.FRA_TOOLBAR)
        self.TXT_MAIN = QtWidgets.QTextBrowser(Dialog)
        self.TXT_MAIN.setObjectName("TXT_MAIN")
        self.verticalLayout.addWidget(self.TXT_MAIN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gridGroupBox.setTitle(_translate("Dialog", "Show"))
        self.CHK_MISCELLANEOUS.setText(_translate("Dialog", "Misc."))
        self.CHK_GRAPHS.setText(_translate("Dialog", "Graphs"))
        self.CHK_FASTA.setText(_translate("Dialog", "FASTA"))
        self.CHK_DATA.setText(_translate("Dialog", "Tables"))
        self.CHK_ALIGNMENTS.setText(_translate("Dialog", "Alignments"))
        self.CHK_COLOURS.setText(_translate("Dialog", "Colours"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.BTN_SAVE.setText(_translate("Dialog", "Save"))


