
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-24T21:38:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6f7f5f1636d2b4b07d880aa534371ad27a5ac9a",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
