stages:
  - build
  - lint
  - test

cache:
  paths:
    - .venv/

virtualenv:
  stage: build
  script:
    - virtualenv -ppython3 .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - pip install -U flake8

flake8:
  stage: lint
  script:
    - source .venv/bin/activate
    - flake8

pytest:
  stage: test
  script:
    - source .venv/bin/activate
    - pytest
  coverage: '/TOTAL.*\s+(\d+\%)/'
