language: python
cache:
- pip
sudo: false
os:
- linux
stages:
- lint
- docs
- test
- deploy
install:
- pip install -q tox-travis tox-pyenv virtualenv wheel | cat
jobs:
  include:
  - stage: lint
    script: python -m tox
    python: 2.7
    env: TOXENV=lint
  - stage: docs
    script: python -m tox
    python: 2.7
    env: TOXENV=docs
  - stage: test
    script: python -m tox
    python: 2.7
    env: TOXENV=py27
    after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: test
    script: python -m tox
    python: 3.4
    env: TOXENV=py34
    after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: test
    script: python -m tox
    python: 3.5
    env: TOXENV=py35
    after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: test
    script: python -m tox
    python: 3.6
    env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
    after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: deploy
    script:
    - export PACKAGE_NAME=$(python setup.py --name)
    - export PACKAGE_VERSION=$(python setup.py --version)
    - python setup.py sdist bdist_wheel
    deploy:
    - provider: pypi
      user: pycontribs
      password:
        secure: beq1+egB93Y9a51NOdrG0ja9zKb+g3/JejoM6kUpm2FU37a9+AU3fAAoGdYcrRqF2fmrBGuYNW29vJEzaDT4YK/FSMNrcipt8U3yyNXJ0oFbVsi0FLeDlBzEFarhY71BguEoJlf+nwCphPXCj/aJPxNiAKYnNCfBdfP0WKH/N5M=
      distributions: sdist bdist_wheel
      skip_cleanup: true
      on:
        tags: true
        repo: pycontribs/tendo
    - provider: releases
      api_key:
        secure: Dz7yMcIBxTKD2zYi0ph9qTz2N0AdmOWD9eI/CMW3DdXh15e4fQqL7O5cr4Sn+FSKHMbUCUoztXwJsYLbrCPB2tH8HliPhSuNzb0CwScRD9wSzQzhli10YPj+Oe2UlPOcIWQFRYTUQ1tfpvfDcvRL7klLDiKUpghJ+xf7crXzqGE=
      file:
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION.tar.gz
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION-py2.py3-none-any.whl
      - ChangeLog
      skip_cleanup: true
      on:
        tags: true
        repo: pycontribs/tendo
