- hosts: [all]
  become: true
  become_user: root
  gather_facts: true
  pre_tasks:
  - name: Install libselinux-python
    yum: name=libselinux-python
  roles:
    - role: ansible-role-bind
      bind_zone_master_server_ip: '{{ dns_server_ip }}'
      bind_zone_name: '{{ domain }}'
      bind_zone_name_servers:
        - ns1
      bind_zone_hosts: '{{ hostnames }}'
      bind_listen_ipv4: ['any']
      bind_allow_query: ['any']


