# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelicComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('last_pushed_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewRelicMetricTimeslice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256)),
                ('values', jsonfield.fields.JSONField()),
                ('new_relic_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_timeslices', to='newrelic_plugin_agent.NewRelicComponent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newrelicmetrictimeslice',
            unique_together=set([('new_relic_component', 'guid')]),
        ),
    ]
