# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1198, 1260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/cfactor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        mainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.draw_frame = QtWidgets.QFrame(self.tab)
        self.draw_frame.setMinimumSize(QtCore.QSize(600, 300))
        self.draw_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.draw_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.draw_frame.setObjectName("draw_frame")
        self.gridLayout_2.addWidget(self.draw_frame, 3, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_etabs = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_etabs.setEnabled(True)
        self.pushButton_etabs.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_etabs.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/export_etabs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_etabs.setIcon(icon1)
        self.pushButton_etabs.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_etabs.setObjectName("pushButton_etabs")
        self.verticalLayout_2.addWidget(self.pushButton_etabs)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/file_extension_pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/report_word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/excel_exports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/file_extension_html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/file_extension_png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_2.raise_()
        self.pushButton_etabs.raise_()
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 5, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(530, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(600, 100))
        self.frame_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.yLateralBox = QtWidgets.QComboBox(self.frame_3)
        self.yLateralBox.setMinimumSize(QtCore.QSize(300, 0))
        self.yLateralBox.setObjectName("yLateralBox")
        self.gridLayout.addWidget(self.yLateralBox, 2, 1, 1, 1)
        self.ySystemBox = QtWidgets.QComboBox(self.frame_3)
        self.ySystemBox.setMinimumSize(QtCore.QSize(150, 0))
        self.ySystemBox.setObjectName("ySystemBox")
        self.gridLayout.addWidget(self.ySystemBox, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 3, 1, 1)
        self.xLateralBox = QtWidgets.QComboBox(self.frame_3)
        self.xLateralBox.setMinimumSize(QtCore.QSize(300, 0))
        self.xLateralBox.setObjectName("xLateralBox")
        self.gridLayout.addWidget(self.xLateralBox, 1, 1, 1, 1)
        self.xSystemBox = QtWidgets.QComboBox(self.frame_3)
        self.xSystemBox.setMinimumSize(QtCore.QSize(150, 0))
        self.xSystemBox.setObjectName("xSystemBox")
        self.gridLayout.addWidget(self.xSystemBox, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_3, 2, 1, 1, 1)
        self.structure_properties_table = QtWidgets.QTableView(self.frame_4)
        self.structure_properties_table.setMinimumSize(QtCore.QSize(530, 320))
        self.structure_properties_table.setMaximumSize(QtCore.QSize(600, 1000))
        self.structure_properties_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.structure_properties_table.setObjectName("structure_properties_table")
        self.gridLayout_6.addWidget(self.structure_properties_table, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 2, 1, 1)
        self.soilPropertiesTable = QtWidgets.QTableWidget(self.frame_4)
        self.soilPropertiesTable.setMinimumSize(QtCore.QSize(250, 250))
        self.soilPropertiesTable.setMaximumSize(QtCore.QSize(200, 600))
        self.soilPropertiesTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.soilPropertiesTable.setAlternatingRowColors(True)
        self.soilPropertiesTable.setRowCount(7)
        self.soilPropertiesTable.setColumnCount(2)
        self.soilPropertiesTable.setObjectName("soilPropertiesTable")
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.soilPropertiesTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.soilPropertiesTable, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(230, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.accText = QtWidgets.QLineEdit(self.frame)
        self.accText.setEnabled(False)
        self.accText.setObjectName("accText")
        self.gridLayout_3.addWidget(self.accText, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.HSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.HSpinBox.setMinimum(1.0)
        self.HSpinBox.setProperty("value", 10.0)
        self.HSpinBox.setObjectName("HSpinBox")
        self.gridLayout_3.addWidget(self.HSpinBox, 6, 1, 1, 1)
        self.ostanBox = QtWidgets.QComboBox(self.frame)
        self.ostanBox.setMinimumSize(QtCore.QSize(130, 0))
        self.ostanBox.setObjectName("ostanBox")
        self.gridLayout_3.addWidget(self.ostanBox, 0, 1, 1, 1)
        self.IBox = QtWidgets.QComboBox(self.frame)
        self.IBox.setObjectName("IBox")
        self.IBox.addItem("")
        self.IBox.addItem("")
        self.IBox.addItem("")
        self.IBox.addItem("")
        self.gridLayout_3.addWidget(self.IBox, 5, 1, 1, 1)
        self.soilType = QtWidgets.QComboBox(self.frame)
        self.soilType.setObjectName("soilType")
        self.soilType.addItem("")
        self.soilType.addItem("")
        self.soilType.addItem("")
        self.soilType.addItem("")
        self.gridLayout_3.addWidget(self.soilType, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.shahrBox = QtWidgets.QComboBox(self.frame)
        self.shahrBox.setMinimumSize(QtCore.QSize(130, 0))
        self.shahrBox.setObjectName("shahrBox")
        self.gridLayout_3.addWidget(self.shahrBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.I_label = QtWidgets.QLabel(self.frame)
        self.I_label.setMouseTracking(False)
        self.I_label.setScaledContents(False)
        self.I_label.setObjectName("I_label")
        self.gridLayout_3.addWidget(self.I_label, 5, 0, 1, 1)
        self.storySpinBox = QtWidgets.QSpinBox(self.frame)
        self.storySpinBox.setMinimum(1)
        self.storySpinBox.setMaximum(100)
        self.storySpinBox.setProperty("value", 3)
        self.storySpinBox.setObjectName("storySpinBox")
        self.gridLayout_3.addWidget(self.storySpinBox, 7, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tAnalaticalGroupBox = QtWidgets.QGroupBox(self.frame_2)
        self.tAnalaticalGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tAnalaticalGroupBox.setCheckable(False)
        self.tAnalaticalGroupBox.setObjectName("tAnalaticalGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tAnalaticalGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tAnalaticalGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 1, 1, 1)
        self.yTAnalaticalSpinBox = QtWidgets.QDoubleSpinBox(self.tAnalaticalGroupBox)
        self.yTAnalaticalSpinBox.setDecimals(4)
        self.yTAnalaticalSpinBox.setMinimum(0.01)
        self.yTAnalaticalSpinBox.setMaximum(10.0)
        self.yTAnalaticalSpinBox.setSingleStep(0.05)
        self.yTAnalaticalSpinBox.setProperty("value", 0.56)
        self.yTAnalaticalSpinBox.setObjectName("yTAnalaticalSpinBox")
        self.gridLayout_5.addWidget(self.yTAnalaticalSpinBox, 1, 2, 1, 1)
        self.xTAnalaticalSpinBox = QtWidgets.QDoubleSpinBox(self.tAnalaticalGroupBox)
        self.xTAnalaticalSpinBox.setDecimals(4)
        self.xTAnalaticalSpinBox.setMinimum(0.01)
        self.xTAnalaticalSpinBox.setMaximum(10.0)
        self.xTAnalaticalSpinBox.setSingleStep(0.05)
        self.xTAnalaticalSpinBox.setProperty("value", 0.56)
        self.xTAnalaticalSpinBox.setObjectName("xTAnalaticalSpinBox")
        self.gridLayout_5.addWidget(self.xTAnalaticalSpinBox, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tAnalaticalGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.tAnalaticalGroupBox)
        self.infillCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.infillCheckBox.setObjectName("infillCheckBox")
        self.verticalLayout.addWidget(self.infillCheckBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_6.addWidget(self.frame_2, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textExport = QtWidgets.QTextEdit(self.tab_2)
        self.textExport.setReadOnly(True)
        self.textExport.setObjectName("textExport")
        self.gridLayout_7.addWidget(self.textExport, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1198, 30))
        self.menuBar.setObjectName("menuBar")
        mainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.IBox.setCurrentIndex(1)
        self.soilType.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ضریب زلزله ویرایش چهارم ۲۸۰۰"))
        self.pushButton_etabs.setToolTip(_translate("mainWindow", "ساخت فایل ایتبز"))
        self.pushButton_etabs.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.label_25.setText(_translate("mainWindow", "راستای y"))
        self.label_8.setText(_translate("mainWindow", "سیستم مقاوم جانبی"))
        self.label_23.setText(_translate("mainWindow", "راستای x"))
        self.label_7.setText(_translate("mainWindow", "سیستم سازه"))
        item = self.soilPropertiesTable.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "soil"))
        item = self.soilPropertiesTable.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "T0"))
        item = self.soilPropertiesTable.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "Ts"))
        item = self.soilPropertiesTable.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "S"))
        item = self.soilPropertiesTable.verticalHeaderItem(4)
        item.setText(_translate("mainWindow", "S0"))
        item = self.soilPropertiesTable.verticalHeaderItem(5)
        item.setText(_translate("mainWindow", "B1"))
        item = self.soilPropertiesTable.verticalHeaderItem(6)
        item.setText(_translate("mainWindow", "B"))
        item = self.soilPropertiesTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "x"))
        item = self.soilPropertiesTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "y"))
        self.label_11.setText(_translate("mainWindow", "خطر نسبی"))
        self.label_2.setText(_translate("mainWindow", "نوع خاک"))
        self.label_6.setText(_translate("mainWindow", "شهر"))
        self.label.setText(_translate("mainWindow", "استان"))
        self.HSpinBox.setWhatsThis(_translate("mainWindow", "ارتفاع ساختمان"))
        self.HSpinBox.setSuffix(_translate("mainWindow", "    متر"))
        self.IBox.setItemText(0, _translate("mainWindow", "0.8"))
        self.IBox.setItemText(1, _translate("mainWindow", "1.0"))
        self.IBox.setItemText(2, _translate("mainWindow", "1.2"))
        self.IBox.setItemText(3, _translate("mainWindow", "1.4"))
        self.soilType.setItemText(0, _translate("mainWindow", "I"))
        self.soilType.setItemText(1, _translate("mainWindow", "II"))
        self.soilType.setItemText(2, _translate("mainWindow", "III"))
        self.soilType.setItemText(3, _translate("mainWindow", "IV"))
        self.label_5.setToolTip(_translate("mainWindow", "<html><head/><body><p>فقط برای کنترل محدودیت های نوع سیستم جانبی استفاده میشود.</p></body></html>"))
        self.label_5.setText(_translate("mainWindow", "تعداد طبقات"))
        self.label_4.setWhatsThis(_translate("mainWindow", "ارتفاع ساختمان"))
        self.label_4.setText(_translate("mainWindow", "ارتفاع"))
        self.I_label.setWhatsThis(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">گروه۱- ساختمانهای «با اهمیت خیلی زیاد»</span><br />این گروه شامل دو دسته زیر است:<br /><span style=\" font-weight:600; font-style:italic; text-decoration: underline;\">الف - ساختمان های ضروری:</span><span style=\" font-weight:600; font-style:italic; text-decoration: underline;\"> </span>این گروه شامل ساختمانهایی است که قابل استفاده بودن انها پس از وقوع زلزله اهمیت خاصی دارد و وقفه در بهره برداری از آنها غیرمستقیم موجب افزایش تلفات و خسارات می شود؛ مانند بیمارستان ها و درمانگاه ها، مراکز آتش نشانی، مراکز و تأسیسات آبرسانی، ساختمانهای نیروگاهها و تأسیسات برقرسانی، برج های مراقبت فرودگاهها، مراکز مخابرات، رادیو و تلویزیون، تأسیسات نظامی و انتظامی، مراکز کمکرسانی و به طور کلی تمام ساختمانهایی که استفاده از انها در نجات و امداد مؤثر می باشد. </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">ب - ساختمانهای خطرزا: </span>این گروه شامل ساختمان ها و تأسیساتی است که خرابی آنها موجب انتشار گسترده مواد سمی و مضر در کوتاهمدت و درازمدت برای محیط زیست می شوند، مانند کارخانه های تولیدکننده مواد شیمیایی خاصی،<br /><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">گروه ۲- ساختمانهای «با اهمیت زیاد»</span><br />این گروه شامل سه دسته زیر است: </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">الف- ساختمانهایی که خرابی آنها موجب تلفات زیاد می شود:</span> مانند مدارس، مساجد، استادیومها، سینما و تئاترها، سالن های اجتماعات، فروشگاه های بزرگ، ترمینالهای مسافری و یا هر فضای سرپوشیده دیگری که محل تجمع بیش از ۳۰۰ نفر در زیر یک سقف باشد.</p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">ب - ساختمانهایی که خرابی آنها سبب از دست رفتن ثروت ملی میگردد:</span> مانند موزه ها، کتابخانه ها، و به طور کلی مراکزی که در آنها اسناد و مدارک ملی و یا آثار پر ارزش دیگری نگهداری میشود. </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">پ – ساختمانها و تأسیسات صنعتی</span> که خرابی آنها موجب آلودگی محیط زیست و یا آتش سوزی وسیع میشود مانند پالایشگاه ها، انبارهای سوخت و مراکز گازرسانی. </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">گروه ۳- ساختمانهای «با اهمیت متوسط»</span> </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">این گروه ساختمانها شامل کلیه ساختمانهای مشمول این آییننامه، بجز ساختمانهای عنوان شده در سه گروه دیگر می باشند، مانند ساختمانهای مسکونی و اداری و تجاری، هتلها، پارکینگهای چند طبقه، انبارها، کارگاهها، ساختمانهای صنعتی گروه</p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\"> ۴- ساختمانهای «با اهمیت کم»</span><span style=\" color:#0000ff;\"> </span></p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">این گروه شامل دو دسته زیر است: </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">الف- ساختمانهایی که خسارت نسبتاً کمی از خرابی آنها حادث میشود</span> و احتمال بروز تلفات جانی انسانی در آنها بسیار کم است، مانند انبارهای کشاورزی و سالن های نگهداری دام. </p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">ب - ساختمانهای موقتی</span> که مدت بهره برداری از آنها کمتر از ۲ سال است.</p></body></html>"))
        self.I_label.setText(_translate("mainWindow", "ضریب اهمیت"))
        self.tAnalaticalGroupBox.setTitle(_translate("mainWindow", "زمان تناوب تحلیلی"))
        self.label_10.setText(_translate("mainWindow", "<html><head/><body><p>Ty<span style=\" vertical-align:sub;\">an</span></p></body></html>"))
        self.yTAnalaticalSpinBox.setSuffix(_translate("mainWindow", "     ثانیه"))
        self.xTAnalaticalSpinBox.setSuffix(_translate("mainWindow", "     ثانیه"))
        self.label_9.setText(_translate("mainWindow", "<html><head/><body><p>Tx<span style=\" vertical-align:sub;\">an</span></p></body></html>"))
        self.infillCheckBox.setToolTip(_translate("mainWindow", "<html><head/><body><p>فقط برای قابهای خمشی فعال می باشد.</p></body></html>"))
        self.infillCheckBox.setText(_translate("mainWindow", "اثر میانقاب"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "مشخصات ساختمان"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "خروجی"))

import resource_rc
