language: python
cache:
- pip
sudo: false
os:
- linux
stages:
- test
- deploy
install:
- pip install -q tox-travis tox-pyenv virtualenv | cat
jobs:
  include:
  - stage: test
    script: python -m tox
    python: 2.7
    env: TOXENV=py27
  - stage: test
    script: python -m tox
    python: 3.4
    env: TOXENV=py34
  - stage: test
    script: python -m tox
    python: 3.5
    env: TOXENV=py35
  - stage: test
    script: python -m tox
    python: 3.6
    env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
  - stage: deploy
    script:
    - export PACKAGE_NAME=$(python setup.py --name)
    - export PACKAGE_VERSION=$(python setup.py --version)
    - python setup.py sdist bdist_wheel
    deploy:
    - provider: pypi
      user: pycontribs
      password:
        secure: B7u10E5+HFXg4jRJFvHL1Z7mTMJfQh+BwKt22NdAnNm0K3xSj0E5h2C6vEHs97xG7vJ36Eh1Dc2W85miFaolJ6efg0DnGAzjBFUWKZhjufO6zXP3e86VpSS/pTNlfcXaswOP+hkVb0Q3zqwSK4dGLOAB8/OTbb8SBWjAndixDzw=
      distributions: sdist bdist_wheel
      skip_cleanup: true
      on:
        tags: true
        repo: pycontribs/wstools
    - provider: releases
      api_key:
        secure: L+4ubjx681BpztL704qBeUKSkfAVr+Ooia2EVMCCaCw4DtOWRdAwhc0P1vWfPfgrMEktEkkx/OHTa5Ha0sPCiosBeTD5AjNY7NChWCmtsTGLkv+RmNtK4QOwkKaMl7D8MQDMbTzF1TDVZ9lik7Ni+dXEOFfDquXU052aoYkvwlA=
      file:
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION.tar.gz
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION-py2.py3-none-any.whl
      - ChangeLog
      skip_cleanup: true
      on:
        tags: true
        repo: pycontribs/wstools
