image: ikus060/docker-debian-py2-py3:stretch

stages:
- test
- publish

# Upgrade python and install dependencies to avoid compiling from sources.
before_script:
- apt-get update && apt-get -qq install python-pysqlite2 libldap2-dev libsasl2-dev rdiff-backup node-less
- pip install pip setuptools --upgrade

# TODO Split this by python version and OS.
test_py27:
  stage: test
  script:
  - pip install tox nose coverage --upgrade
  - python setup.py build
  - export TOXENV=`tox --listenvs | grep "^py27" | tr '\n' ','`
  - tox --sitepackages
  
test_py3: 
  stage: test
  script:
  - pip install tox nose coverage --upgrade
  - python setup.py build
  - export TOXENV=`tox --listenvs | grep "^py3" | tr '\n' ','`
  - tox --sitepackages
  
# TODO Publish coverage repport
# TODO Publish testcases repport

publish_nexus:
  stage: publish
  script:
  - pip install wheel twine --upgrade
  - python setup.py sdist bdist_wheel
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  only:
  - tags
  script:
  - pip install wheel twine --upgrade
  - python setup.py sdist bdist_wheel
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  
github_push:
  stage: publish
  script:
  - git push --force https://${GITHUB_USR}:${GITHUB_PWD}@github.com/ikus060/rdiffweb.git refs/remotes/origin/${CI_COMMIT_REF_NAME}:refs/heads/${CI_COMMIT_REF_NAME}
  - git push https://${GITHUB_USR}:${GITHUB_PWD}@github.com/ikus060/rdiffweb.git --tags
  
