language: python
python:
  - '2.7'
  - '3.6'
install: pip install -r requirements-dev.txt
script: python setup.py test
deploy:
  - provider: pypi
    user: rjosephwright
    password:
      secure: yubuBncWv1cTrZXoWIQ0vCq66V2t3fPtGxVz4khpuYUVhkngzxgLaCqyNNNViqNwULh5xVjhoLh++ydlDUe7CgP81pRRSvzOODXwOhbJ/B9i1yxygMG1HTbbrNg5GRwfFwyDAHGpnKkxtshIC+PDrsAFuFwPVrKyDVpwBrwuB9xBsxcGspkL5D3WUjRnWFEbb3geWlL2amuRHVwPBzbIq2rEDHdl5wgR8UWNwZd24HgXc4LwitM6FYan9blv9HLugYOMDg0RWp3pwdemlJe7xuVWkj5GVFlEXxmDQaq+/rVyBNzRh5oPNHWFovHClF4A5LpWqq5vpcwcgd9TQOhF9dnqu6NESCHWW9kYR7UTG1XynNZzTZzLBr7g6N40W4Ry/vKqFIqIECzwtfeta5plPHirh3BpgraPoOqdrw0IXdBXXnAcHPkYR3jwDtPVgXGHbFguwonG3HK+nUMBRNdi1fsRqluk+WPBxGKUjWrx1IVToiKpsfXEe93DbiGIacHbddjrRFuXaQLMgwvxy9cL4CFK/Feb6tPD7M3T3NBkbJfx/XgdOEZmz59jYS80xcz3pwXDSQHamHXLK6Vdwh6+W+mj7gjfHq7hPu9UI1Mee+J0TvX2FcUQ0TggZffM2WFS2q4as7dDLawLktdNLjzlNHQr57TmO937UVWhagd80tU=
    on:
      tags: true
    distributions: sdist bdist_wheel
