sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOXENV="django18"
  - TOXENV="django110"
  - TOXENV="django111"
  - TOXENV="djangodev"

matrix:
  fast_finish: true
  exclude:
    - python: "3.6"
      env: TOXENV="django18"
    - python: "3.6"
      env: TOXENV="django110"

    - python: "3.4"
      env: TOXENV="django110"
    - python: "3.4"
      env: TOXENV="django111"

    - python: "2.7"
      env: TOXENV="djangodev"

  allow_failures:
    - env: TOXENV="djangodev"

before_install:
- pip install codecov coverage==3.6 tox

script:
  - tox

after_success:
- coverage xml -i
- codecov

branches:
  only:
    - master
