from collections import OrderedDict
investigations_dict=OrderedDict()
import json

investigations_dict['Haematology'] = [
    'CBC',
    'B/S for Mps',
    "Blood Smear",
    'Periperal Film',
    'Blood grouping',
    'Cross matching',
    'ESR', 'RBS', 'FBS',
    'C Reactive Protein',
    'Sickling Test',
    'Hb Electrophoresis',
    'Hb',
    "HBA1C(Glycated Heamoglobin)",
    'CD4 Count',
    'Bleeding Time',
    'Clotting Time',
    'PT', 'aPTT', 'D Dimers',
    'Bone Marrow Biopsy',
    "Filariae",
    "LEISHMANIA TEST",
]

investigations_dict['Microbiology'] = [
    'Urinalysis',
    "Uristick",
    'Gram Staining',
    'ZN Staining',
    'Stool analysis',
    'Urine Culture',
    'Blood Culture',
    'Sputum Culture',
    'CSF Analysis',
    'CSF Culture',
    'Ascitic Fluid Analysis',
    'Ascitic Fluid Culture',
    'Pleural Fluid Analysis',
    'Pleural Fluid Culture',
    'High Vaginal Swab',
    'Urethral Swab',
    'Semen Analysis',
    "Urine for Schistosomiasis",
    "Lymph Node Aspirate for ZN",
    "Semen Culture",
    "TOLUIDINE BLUE STAINING",
]

investigations_dict['RFTs'] = [
    'Serum Creatinine',
    'Urea'
]

investigations_dict['Serology'] = [
    'Malaria RDT',
    'Widal Test',
    'BAT',
    'RPR',
    'VDRL',
    'RCT',
    'HBsAg',
    'H Pylori',
    'Serum Beta hCG',
    'Typhoid Antigen',
    'Urine LAM',
    'Urine hCG',
    'CSF CrAg',
    'TPHA',
    'HepB Viral Load',
    'RF',
]

investigations_dict['LFTs'] = [
    'AST',
    'ALT',
    'ALP',
    'GGT',
    'Albumin',
    'Total Protein',
    'Total Bilirubun',
    'Direct Bilirubin'
]

investigations_dict['Serum Electrolytes'] = [
    'Na',
    'K',
    'Cl',
    'Ca2',
    'Mg2',
    "Phosphorous",]

investigations_dict['Lipid Profile'] = [
    'VLDL',
    'LDL',
    'HDL',
    'TG',
    'TChol'
]

investigations_dict["Clinical Chemistry"]=[
    "CEA",
    "CKMB",
    "CPK(CK_NAC/Creatinine Kinase)",
    "COOMBS TEST DIRECT",
    "COOMBS TEST INDIRECT",
    "Lithium Level",
    "Microglobulin",
    "CA 125",
    "CD4/CD8",
    "Creatinine (Urine)",
    "24hr Urine Protein",
    "Urea Clearance Test",
    "Urinary Uric Acid",
    "Serum Uric Acid",
    "Urine Chloride",
    "Fecal Occult Blood",
    "Creatinine Clearance Test",
    "CA 19",
    "C PEPTIDE",
    "FREE PSA",
    "Globulins",
    "FIB (Fibrinogen)",
    "G6PD",
    "H PYLORI STOOL Ag",
    "HSV IgG TYPE Ab",
    "HSV IgM TYPE Ab",
    "HBV Core Ab",
    "HBV Core IgM Ab",
    "HSV IgG/IgM TYPE",
    "Hepatitis E IGG",
    "Hepatitis E IGM",
    "Hepatitis B (HBV) DNA Viral Load",
    "Hepatitis Envelope(Ag/Ab)",
    "Hepatitis Envelope(Ag)",
    "HBe Ag",
    "HBc IgG/IgM",
    "Hepatitis C Antigen",
    "HAIN Test",
    "BILHARZIA 1gG",
    "Drugs of Abuse Panel",
    "Plasma PH",
    "Serum Ketones",
    "ABGs Panel",
    "Quantiferon Gold TB Blood Test",
    "SERUM FERRITIN",
    "SERUM VIT B12",
    "SCHISTOSOMAL ANTIBODIES",
    "Serum Gastrine",
    "Serum IgE",
    "TOXO Ig G",
    "TOXO Ig M",
    "Troponin T Assay",
    "ANTI NUCLEAR ANTIBODY(ANA)",
    "REDUCING SUGAR",
]

investigations_dict["Endocrine"]=[
    "Anti_Mullerian Hormone_MIS",
    "Hormonal Receptor Status test (Estrog+Prog)",
    "Hormonal Receptor Status test(her2+neu+ea1+ea3) + (ER+PR)",
    "Hormonal Receptor Status test(her2+neu+ea1+ea3)",
    "FREE T3",
    "FREE T4",
    "TSH",
    "FSH",
    "LH",
    "Serum Amylase",
    "Serum Lipase",
    "Serum Calcitonin",
    "Vitamin D Levels",
    "Parathyroid Hormone(PTH)",
    "TESTOSTERONE",
    "Typhoid IgG",
    "Typhoid IgM",
    "ACTH PROFILE",
    "24Hrs Urine Cortisol",
    "Progesterone",
    "Prolactin",
    "Serum Cortisol",
    "Serum Estrogen",
    "Serum Progesterone",

]

investigations_dict["Ultrasound Scan"]=[
    "Ultrasound Scan (Abdomen)",
    "Ultrasound Scan  (Chest)",
    "Ultrasound Scan (Abdominal)",
    "Ultrasound Scan (Brain)",
    "Ultrasound Scan (Breasts)",
    "Ultrasound Scan (Eyes)",
    "Ultrasound Scan (Jaw)",
    "Ultrasound Scan (Knee [each])",
    "Ultrasound Scan (Lymph nodes)",
    "Ultrasound Scan (Scrotal)",
    "Ultrasound Scan (Shoulder [each])",
    "Ultrasound Scan (Tendon or Mass)",
    "Ultrasound Scan(Thyroid)",
    "Ultrasound Scan (Transrectal)",
    "Transvaginal Ultrasound scan",
    "Biophysical profile scan",
    "Doppler U/S Scan(Renal)",
    "Doppler U/S Scan (Carotid)",
    "Doppler U/S Scan (Umbilical Cord)",
    "Doppler U/S Scan (arteries)",
    "Doppler U/S Scan (veins)",
    "Ultrasound Scan(3D)",
    "Ultrasound guided Liver Biopsy",
    "Ultrasound guided peritoneum aspiration",
    "Ultrasound Scan (Pelvic)",
    "Ultrasound Scan (Obstetric)",
]

investigations_dict["XRAYS"]=[
    "Xray Ankle",
    "Xray Cervical Spine",
    "Xray Chest PA",
    "Xray Chest AP",
    "Xray Chest AP & Lateral",
    "Xray Elbow",
    "Xray Femur",
    "Xray Foot",
    "Xray Fore Arm",
    "Xray Hand",
    "Xray Hip",
    "Xray Humerus",
    "Xray Jaw",
    "Xray Knee",
    "Xray Lumber Sacral [AP + LP]",
    "Xray Lumber Spine",
    "Xray Pelvis",
    "Xray Post nasal space",
    "Xray Shoulder",
    "Xray Skull",
    "Xray Thoracic Lumber",
    "Xray Thoracic Spine",
    "Xray Tibia & Fibula",
    "Xray Wrist",
    "Barium Enema",
    "Barium Meal",
    "Barium Meal and Follow Thru",
    "Barium Swallow",
    "Sinuses",
    "Mandible",
    "Paranasal sinuses",
    "Retrograde Pyelogram",
    "XRay Abdomen(Erect)",
    "XRAY (Venography)",
    "CXR (Lateral)",
    "Intravenous Pyelogram(IVP)",
    "Xray Film reprint",
    "Xray (Mammogram)",
]

investigations_dict["CT SCANS"]=[
    "CT Brain Angiogram",
    "CT Myelogram",
    "CT Scan [Chest]",
    "CT Scan Multiphase Liver",
    "CT Scan Abdomen & Pelvis",
    "CT Scan Brain",
    "CT Scan Brain wt IV Contrast",
    "CT Scan Cervical Spine",
    "CT Scan Hip Joint",
    "CT Scan Knee Joint",
    "CT Scan Lumbar Spine",
    "CT Scan Neck",
    "CT Scan Orbits",
    "CT Scan Para nasal Sinuses",
    "CT Scan Pelvis",
    "CT Scan Shoulder Joint",
    "CT Scan Pituitary Fossa (Sellar Turcica)",
    "CT Scan Thoracic Spine",
    "CT Scan Multiphase Pancreas",
    "CT Scan Multiphase Kidney",
    "CT Scan Angiography  (Cerebral)",
    "CT Scan Angiography  (Abdomen)",
    "CT Scan Angiography  (Peripherals)",
    "CT Scan Angiography  (Chest)",
    "CT Scan Angiography  (Neck)",
    "CT Scan Joints (Ankle)",
    "CT Scan Joints (TMJ)",
    "CT Scan Urologic (KUB)",
    "HIGH RESOLUTION CT(HRCT) Lung",
    "CT Scan Abdomen",
    "CT Scan Ventricular Function",
    "CT Scan Coronary Angiogram",
    "CT Scan Cardiac Calcium Scoring",
    "CT Scan Total Body scan",
    "CT Urography/KUB",
    "CT Film reprint",
]

investigations_dict["Pathology"]=[
"Cytology Asparate",
"FNAC PROCEDURE",
"IMMUNO_HISTOCHEMISTRY TEST",
"Mantoux Test",
"Renal Tuberculosis(Urine Specimens)",
"PAP Smear(Cytology)",
"SKIN SNIP",
"TISSUE PROCESSING",
"TISSUE GLOSSING",
"Postmortem",
"Urine Cytology",
"Tumor histology",
"Frozen Section analysis"
]

investigations_dict["Cardiac"]=[
    "Electrocardiogram(ECG)",
    "Echocardiogram(Echo)"
]

investigations_dict["Psychiatric"]=["ElectroEncephalogram(EEG)"]


