language: python
python:
- '3.6'
script:
- pytest
services:
- redis-server
deploy:
  password:
    secure: IXbD5vEXML8/6jQ5nB4fCDUzvu8oKCxpUaaKeY1q2708+Wc7uCh55e4gkdva0cpz7AC5jytEgbdH8Whc94pJF1t8Euy9IqvgPM4gfSUlqbSfITGeZPMJb/ThI4Hsgyp99HGXQhLklJhH1wvLsmOX8/JmN5cZY1oH9hHIrEfR82oCDb/NgQJdCmR9tfUpdxs3VxJZ31dpylY8C4bRHciJkt7tauatA7/KOD1Jlkz5yQTX64kW2LwKp8DZ0p0aboxzr11gBRIU0Nw53QzXIZN65Ov+4O7jFNuFzX/PsBJD89uVfezZRhBkEnYAwO5J6w9O9NHoUltFc+N6eLnAQrasVAmgLy4DQjtZBZfzYO4gzj7CD9yn7eUBDCv8Alka3ndAAZQAPCKdYZtytAR9AH3ESn5+t3wSR9qAAp6MrcAKjYkKIB2n5MM1nf8MIFIkvzhtbuxNOfb+A7rpj4KZBx+VIWZdrCRuypesqOi6Hm4W7R00/3qVokKhoi5EKvdXODz1aK1IHV6pUC4Qhn0VdCoRoWjgydpiJUZxBOQGY/uSKLLE5aLO/3BwcI9AJ3GaID0XTZzWq137PChMISSjdXSsJzkiyBi1TZLdET0Vc5dcstOxsPgoDJHA7EtNmL7RSCuHm4ntxRi1hukTCmpOU2T57w1C2Y7qdouO2Ji+iyAgPZQ=
  provider: pypi
  user: dmarkey
  on:
    tags: true
