dist: trusty
sudo: false
language: python

python:
- 2.7
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: e9oFIz0EcmVsY6zJaHOWjFwXMPxkKMLt+1nOfXEiLQybCMzeVEYeAHQh7URTPlMobBfl3P52IC9sP7/kJIJPqfwqXL0ANxPzOfc7K2X7WD63/MGXNWDTdv6nXkLbfU1m8TYz2ZizE31E8HDN8zJB2ErFLjDSXfjak59MpuM/Q54K5ZMOlHklE7kZlBVQe1ilgndoUN2cf4K/XGjhVH8b7xgCKRknpzQDM5kMsJOK8lpTlzTxeOzB2m1zfpWnGHFCqk6Pobi8YDkmRm6ogIufTyuOwuTcAI/k50gXR+LPtmVomoLp27qJCiuLvq+m4QplCVpMHPmLQzmTq0jV7g4VxafQoNqaAGadW97x8Qk1eEY1deP0RZ8jf9tpbikidKFfeWR/qZNRro589XD6vvDPuJ0TBOAVuOFDH9A14B4FyWy4HQkTvRLNsahjXJ48LMKV+hnOTuqIh8Px8NGZ3UQbY2U2y+g62jVcNvYAuzRmg0t4D7S75mQ+h6LL3dKDV0q2Oe7G/Psrw3JmkwRwFIJVboUoRT7/o/9F9IAelWSAENR0+kEGvv/3QUcNYX6RSkp5Gyi6BVG5EeDEfVcAwm8fQef3fJ2+EUUfFEdyugWPByKZRfh9yn4n09nGbZOXyViJnPmTT5sHaR7Y0saYwNSgK3WAeEJy6e1pJmiCyOaynNg=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox tox-venv

script: tox
