# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/satarsa/python/monocle/ui/ui_mwmonocle.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWMonocle(object):
    def setupUi(self, MWMonocle):
        MWMonocle.setObjectName("MWMonocle")
        MWMonocle.resize(1058, 843)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/monocle"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWMonocle.setWindowIcon(icon)
        MWMonocle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MWMonocle)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelT0 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelT0.setFont(font)
        self.labelT0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelT0.setObjectName("labelT0")
        self.verticalLayout.addWidget(self.labelT0)
        self.plot0 = GraphicsLayoutWidget(self.groupBox)
        self.plot0.setObjectName("plot0")
        self.verticalLayout.addWidget(self.plot0)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelT1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelT1.setFont(font)
        self.labelT1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelT1.setObjectName("labelT1")
        self.verticalLayout_2.addWidget(self.labelT1)
        self.plot1 = GraphicsLayoutWidget(self.groupBox_2)
        self.plot1.setObjectName("plot1")
        self.verticalLayout_2.addWidget(self.plot1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelT2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelT2.setFont(font)
        self.labelT2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelT2.setObjectName("labelT2")
        self.verticalLayout_3.addWidget(self.labelT2)
        self.plot2 = GraphicsLayoutWidget(self.groupBox_3)
        self.plot2.setObjectName("plot2")
        self.verticalLayout_3.addWidget(self.plot2)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelT3 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.labelT3.setFont(font)
        self.labelT3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelT3.setObjectName("labelT3")
        self.verticalLayout_4.addWidget(self.labelT3)
        self.plot3 = GraphicsLayoutWidget(self.groupBox_4)
        self.plot3.setObjectName("plot3")
        self.verticalLayout_4.addWidget(self.plot3)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        MWMonocle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MWMonocle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 49))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MWMonocle.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MWMonocle)
        self.statusbar.setObjectName("statusbar")
        MWMonocle.setStatusBar(self.statusbar)
        self.actionSetLogDirectory = QtWidgets.QAction(MWMonocle)
        self.actionSetLogDirectory.setObjectName("actionSetLogDirectory")
        self.actionHistory = QtWidgets.QAction(MWMonocle)
        self.actionHistory.setObjectName("actionHistory")
        self.actionQuit = QtWidgets.QAction(MWMonocle)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtWidgets.QAction(MWMonocle)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.actionSetLogDirectory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionHistory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MWMonocle)
        QtCore.QMetaObject.connectSlotsByName(MWMonocle)

    def retranslateUi(self, MWMonocle):
        _translate = QtCore.QCoreApplication.translate
        MWMonocle.setWindowTitle(_translate("MWMonocle", "Monocle"))
        self.groupBox.setTitle(_translate("MWMonocle", "Sensor 0"))
        self.labelT0.setText(_translate("MWMonocle", "Temperature: 00.0 C"))
        self.groupBox_2.setTitle(_translate("MWMonocle", "Sensor 1"))
        self.labelT1.setText(_translate("MWMonocle", "Temperature: 00.0 C"))
        self.groupBox_3.setTitle(_translate("MWMonocle", "Sensor 2"))
        self.labelT2.setText(_translate("MWMonocle", "Temperature: 00.0 C"))
        self.groupBox_4.setTitle(_translate("MWMonocle", "Sensor 3: yaw"))
        self.labelT3.setText(_translate("MWMonocle", "Temperature: 00.0 C"))
        self.menuFile.setTitle(_translate("MWMonocle", "&File"))
        self.menuHelp.setTitle(_translate("MWMonocle", "&Help"))
        self.actionSetLogDirectory.setText(_translate("MWMonocle", "Set log directory..."))
        self.actionSetLogDirectory.setShortcut(_translate("MWMonocle", "Ctrl+L"))
        self.actionHistory.setText(_translate("MWMonocle", "History"))
        self.actionHistory.setShortcut(_translate("MWMonocle", "Ctrl+H"))
        self.actionQuit.setText(_translate("MWMonocle", "Quit"))
        self.actionQuit.setShortcut(_translate("MWMonocle", "Ctrl+Q"))
        self.actionAbout_Qt.setText(_translate("MWMonocle", "About Qt..."))

from pyqtgraph import GraphicsLayoutWidget
from . import resources_rc
