stages:
  - build-env
  - build
  - deploy

build-env:
  stage: build-env
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/faucetsdn/faucet/dbuilder:latest -f ci/Dockerfile .
    - docker push registry.gitlab.com/faucetsdn/faucet/dbuilder:latest
  only:
      - tags

build-package:
  stage: build
  image: registry.gitlab.com/faucetsdn/faucet/dbuilder
  script:
    - cd /builds/faucetsdn/faucet
    - TAG="git describe --tags"
    - TAG=$($TAG)
    - TAG="${TAG//[!0-9.-]/}"
    - apt-get upgrade -y && mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='maintainers@faucet.nz' && export DEBFULLNAME='Faucet Maintainers'
    - debchange --newversion $TAG -b "New upstream release"
    - fakeroot debian/rules binary
    - mkdir build
    - mv ../*.deb build/
  artifacts:
    paths:
      - build/*
  only:
      - tags

deploy-package:
  stage: deploy
  image: registry.gitlab.com/faucetsdn/faucet/dbuilder
  script:
    - cd /builds/faucetsdn/faucet/build
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet/debian/jessie *.deb
    - package_cloud push faucetsdn/faucet/debian/stretch *.deb
    - package_cloud push faucetsdn/faucet/debian/buster *.deb
    - package_cloud push faucetsdn/faucet/ubuntu/xenial *.deb
    - package_cloud push faucetsdn/faucet/ubuntu/yakkety *.deb
    - package_cloud push faucetsdn/faucet/ubuntu/zesty *.deb
    - package_cloud push faucetsdn/faucet/ubuntu/artful *.deb
    - package_cloud push faucetsdn/faucet/ubuntu/bionic *.deb
  only:
      - tags
