# -*- coding:utf-8 -*-
PARTY_STATUS_TEST = 0
PARTY_STATUS_USING = 1
PARTY_STATUS_GIVEUP = 2
PARTY_STATUS_STOP = 4
CHOICES_PARTY_STATUS = (
    (PARTY_STATUS_TEST, u'测试中'),
    (PARTY_STATUS_USING, u'正式使用'),
    (PARTY_STATUS_GIVEUP, u'放弃'),
    (PARTY_STATUS_STOP, u'停止使用')
)


# WORKER_STATUS_WORKING = 1
# WORKER_STATUS_QUIT = 2
# WORKER_STATUS_VACATION = 4
#
# CHOICE_WORKER_STATUS = (
#     (WORKER_STATUS_WORKING, u'在职'),
#     (WORKER_STATUS_QUIT, u'离职'),
#     (WORKER_STATUS_VACATION, u'休假')
# )
