---

dependencies: []

galaxy_info:
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Configure and manage LXC'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
  galaxy_tags:
  - system
  - container
  - linux
