---
# tasks file for freckles-io.webserver

- name: "[fail if unsupported webserver]"
  fail: msg="webserver '{{ webserver_type }}' not supported. Only 'nginx' is allowed so far."
  when: webserver_type != 'nginx'

- name: "[setting up certificates for https]"
  include_tasks: letsencrypt.yml
  when: webserver_enable_https

- name: "[setting up {{ webserver_type }}]"
  include_tasks: "{{ webserver_type }}.yml"

- name: "[setting up PHP]"
  include_tasks: php.yml
  when: webserver_enable_php

- name: "[misc tasks]"
  include_tasks: misc.yml
