language: python
python:
- '3.6'
cache: pip
git:
  depth: 1
install: pip install -r requirements.txt
stages:
- prepare cache
- test
- deploy

jobs:
  include:
  - stage: prepare cache
    script: true
  - stage: test
    script: chmod +x test.sh && ./test.sh
  - stage: deploy
    script: skip
    skip_cleanup: true
    deploy:
      on:
        tags: true
        branch:
        - master
        - /?(\d+\.)?(\d+\.)?(\*|\d+)$/
      provider: pypi
      user: 73VW
      password: $PYPI_PASSWORD
notifications:
  email:
    on_failure: never
