# Constant
UF_VALID_CONFIG_FILE = 0xf1f2f3f4

# UF_SYS_PARAM
UF_SYS_TIMEOUT = 0x62
UF_SYS_TEMPLATE_SIZE = 0x64
UF_SYS_ENROLL_MODE = 0x65
UF_SYS_SECURITY_LEVEL = 0x66
UF_SYS_ENCRYPTION_MODE = 0x67
UF_SYS_SENSOR_TYPE = 0x68
UF_SYS_IMAGE_FORMAT = 0x6c
UF_SYS_MODULE_ID = 0x6d
UF_SYS_FIRMWARE_VERSION = 0x6e
UF_SYS_SERIAL_NUMBER = 0x6f
UF_SYS_BAUDRATE = 0x71
UF_SYS_AUX_BAUDRATE = 0x72
UF_SYS_ENROLLED_FINGER = 0x73
UF_SYS_AVAILABLE_FINGER = 0x74
UF_SYS_SEND_SCAN_SUCCESS = 0x75
UF_SYS_ASCII_PACKET = 0x76
UF_SYS_ROTATE_IMAGE = 0x77
UF_SYS_ROTATION = 0x78
UF_SYS_SENSITIVITY = 0x80
UF_SYS_IMAGE_QUALITY = 0x81
UF_SYS_AUTO_RESPONSE = 0x82
UF_SYS_NETWORK_MODE = 0x83
UF_SYS_FREE_SCAN = 0x84
UF_SYS_PROVISIONAL_ENROLL = 0x85
UF_SYS_PASS_WHEN_EMPTY = 0x86
UF_SYS_RESPONSE_DELAY = 0x87
UF_SYS_MATCHING_TIMEOUT = 0x88
UF_SYS_BUILD_NO = 0x89
UF_SYS_ENROLL_DISPLACEMENT = 0x8a

UF_SYS_LIGHTING_CONDITION = 0x90
UF_SYS_FREESCAN_DELAY = 0x91

UF_SYS_FAST_MODE = 0x93
UF_SYS_WATCHDOG = 0x94
UF_SYS_TEMPLATE_TYPE = 0x96
UF_SYS_ENHANCED_PRIVACY = 0x97
UF_SYS_FAKE_DETECT = 0x98
# UF_SYS_MAX_TEMPLATE				= 0x99, //hclee, 140428
UF_SYS_CHECK_LATENT = 0x9a
UF_SYS_VOLTAGE_WARNING = 0x9b
UF_SYS_POWEROFF_TIMEOUT = 0x9c
# UF_SYS_EXPOSURE = 0x9d
UF_SYS_PROTOCOL_INTERFACE = 0X9e

# UF_CONFIG_TYPE
UF_CONFIG_PARAMETERS = 0x01
UF_CONFIG_GPIO = 0x02
UF_CONFIG_IO = 0x04
UF_CONFIG_WIEGAND = 0x08
UF_CONFIG_USER_MEMORY = 0x10


all_system_parameter = [
UF_SYS_TIMEOUT,
UF_SYS_TEMPLATE_SIZE,
UF_SYS_ENROLL_MODE,
UF_SYS_SECURITY_LEVEL,
UF_SYS_ENCRYPTION_MODE,
UF_SYS_SENSOR_TYPE,
UF_SYS_IMAGE_FORMAT,
UF_SYS_MODULE_ID,
UF_SYS_FIRMWARE_VERSION,
UF_SYS_SERIAL_NUMBER,
UF_SYS_BAUDRATE,
UF_SYS_AUX_BAUDRATE,
UF_SYS_ENROLLED_FINGER,
UF_SYS_AVAILABLE_FINGER,
UF_SYS_SEND_SCAN_SUCCESS,
UF_SYS_ASCII_PACKET,
UF_SYS_ROTATE_IMAGE,
UF_SYS_ROTATION,
UF_SYS_SENSITIVITY,
UF_SYS_IMAGE_QUALITY,
UF_SYS_AUTO_RESPONSE,
UF_SYS_NETWORK_MODE,
UF_SYS_FREE_SCAN,
UF_SYS_PROVISIONAL_ENROLL,
UF_SYS_PASS_WHEN_EMPTY,
UF_SYS_RESPONSE_DELAY,
UF_SYS_MATCHING_TIMEOUT,
UF_SYS_BUILD_NO,
UF_SYS_ENROLL_DISPLACEMENT,

UF_SYS_LIGHTING_CONDITION,
UF_SYS_FREESCAN_DELAY,

UF_SYS_FAST_MODE,
UF_SYS_WATCHDOG,
UF_SYS_TEMPLATE_TYPE,
UF_SYS_ENHANCED_PRIVACY,
UF_SYS_FAKE_DETECT,
# UF_SYS_MAX_TEMPLATE				= 0x99, //hclee, 140428
UF_SYS_CHECK_LATENT,
UF_SYS_VOLTAGE_WARNING,
UF_SYS_POWEROFF_TIMEOUT,
# UF_SYS_EXPOSURE,
UF_SYS_PROTOCOL_INTERFACE,
]


