
__title__ = 'cmpa'
__description__ = 'Comparison utility'
__url__ = 'https://github.com/jamesabel/cmpa'
__download_url__ = 'https://github.com/jamesabel/cmpa/archive/master.zip'
__version__ = '0.0.3'
__author__ = 'James Abel'
__author_email__ = 'j@abel.co'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 James Abel'
