---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.apt_mark default variables
# =================================

# .. contents:: Sections
#    :local:


# General configuration [[[
# -------------------------

# .. apt_mark__enabled [[[
#
# Enable or disable support for marking APT package state.
apt_mark__enabled: True
                                                                   # ]]]
                                                                   # ]]]
# APT package state configuration [[[
# -----------------------------------

# These lists define the APT packages which the role will operate on, and their
# desired state. See :ref:`apt_mark__ref_packages` for more details.

# .. apt_mark__default_packages [[[
#
# List of APT package states defined by the role
apt_mark__default_packages: []

                                                                   # ]]]
# .. apt_mark__packages [[[
#
# List of APT package states which should be applied on all hosts in the
# Ansible inventory.
apt_mark__packages: []

                                                                   # ]]]
# .. apt_mark__group_packages [[[
#
# List of APT package states which should be applied on hosts in a specific
# Ansible inventory group.
apt_mark__group_packages: []

                                                                   # ]]]
# .. apt_mark__host_packages [[[
#
# List of APT package states which should be applied on specific hosts in the
# Ansible inventory.
apt_mark__host_packages: []

                                                                   # ]]]
# .. apt_mark__dependent_packages [[[
#
# List of APT package states defined by other Ansible roles via role dependent
# variables.
apt_mark__dependent_packages: []

                                                                   # ]]]
# .. apt_mark__combined_packages [[[
#
# Variable which combines all of the APT state lists and is passed to the role
# tasks.
apt_mark__combined_packages: '{{ apt_mark__default_packages
                                 + apt_mark__dependent_packages
                                 + apt_mark__packages
                                 + apt_mark__group_packages
                                 + apt_mark__host_packages }}'
                                                                   # ]]]
                                                                   # ]]]
