
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-23T19:17:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cef1668bfdb00c37c1230ab54068e0b5006014ed",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
