language: python
sudo: false
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: stephenfin
  password:
    secure: lhYw9N+25YhBT8iSd2dYSbTsiJ02JvftWbU9KFDE3cXtKnquIaqUXvJfRtKM/Pdcwnvez6EBRsEz8zxHvUf+0ui9lKyjv2T/0p/bU9T3WFiZURkWlj9P1It0OZNeQ0f4ZteAz9i+144u3vRamJnZUyg7uCbi/CTrEXZuIbws/VBo/js0Ir/KpKnBZqJ/rMS/GfEbgi34Uy8cuJ6Yz4oFpoQhDPGTyqO165kbOm3Oz6Z9JuWR8U+x7WaVCjk65tdAzKmxR3V6YV4IwrSxVVrDL0SH65ME3eNAmQopokGtiP0fH1HJv+KvFHXrru3391dEwaoBTIkJPCzrtvJoF92NO6vHhGfUDfc4KEr4QOoyD3WoBBMg3ufG0ZlDKozaeQO+w2eTvfe4IpxQo/UyKqs1a2b/YbEDdqBLooBZ2ms4C+D8Ua9uZgYu3d974Er0qIgAeHLYGpFTkxW1gc2bB5ikB/ziV3du+WipA7pJo0Az5h4PRlmMIkvRCOAzoUmr/FA20h4I4t2aXbo9WJInVeJxdiLlWO0Gs6GfzXrLFYinf2kxt6jfV6EBpjQAinxwJ6xLjYe6z5TjoU3Fm6XeviEXavYEGKyl46OqLcQrKmcGQqlp1xOMWBk13V2TLdipHFUmumSS+FUwReWnHWxfw0ASk+zg571fZXtYZ/XTHl59QWk=
  on:
    tags: true
  distributions: sdist bdist_wheel
