language: python
matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
install:
- make init
- pip install coveralls
script:
- tox
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make coverage; fi
after_success: coveralls
deploy:
  # test pypi
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: Wheerd
    password:
      secure: iyIXJndQ5a6vzNG0GdpdGoqUE7tGXUxGGcYPF3pVE3K0TFDWaaT4ltRyn6yIHWhPngY0e5aqSlfkSwFf1W/LnTLCDYqnw9NGlorlnZA6PsieTlfFbPIn+J3fQrYFyDoS2wS00Iux+uigW9ZurMmkRl0X+OfpkuV5bwYu8gXFute/ZXcT7Im+NB/OD8vsqU1iGkAmE+SMhDrpP3KWI2vf+lGCBYf38py1f7O800GVsCW9ezEJ37+lqoQ4ImFvDDXUTlFXqhcNyYOecVmmORz0dyFzrXM5YcRlAQDJtPoPmqSjGTPxSuQKsrRRn7PUuRBMArIk9XBErk3ZvcUhYecR6SLulDUI09veY4KbJ4xG/czokP9VbQ96cAzILhNn/lHFFqhg7hkt8PSW3GlUuOkIBt8TFh0MjVPfx0vi0B7DTDFR3Dyvxi0psCFKPNLl4G5IQXIQ5vK5rErN/j5KIo1qSxPgMTT709sFLQ2lRejWDE3OlNn7+RQDlz4LAjnKqGVFST8NbRR/kl3FA4TZNmOeZpIEDlULjGIURW3iJZZne/zeLmoxUZWvDQD8Rn/TZeyiv8zrVMS7hM6rvcTYRUc+mUmVZioHvYl0tXd1lMtGEaMOJA0COvUP/+wEt/lBGCpLHL0vnyX0gPJ0Esf6yEM0CtIVfWU4YMQUM4KUdM+Ce74=
    on:
      branch: master
      tags: false
      distributions: sdist bdist_wheel
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
  # production pypi
  - provider: pypi
    user: Wheerd
    password:
      secure: iyIXJndQ5a6vzNG0GdpdGoqUE7tGXUxGGcYPF3pVE3K0TFDWaaT4ltRyn6yIHWhPngY0e5aqSlfkSwFf1W/LnTLCDYqnw9NGlorlnZA6PsieTlfFbPIn+J3fQrYFyDoS2wS00Iux+uigW9ZurMmkRl0X+OfpkuV5bwYu8gXFute/ZXcT7Im+NB/OD8vsqU1iGkAmE+SMhDrpP3KWI2vf+lGCBYf38py1f7O800GVsCW9ezEJ37+lqoQ4ImFvDDXUTlFXqhcNyYOecVmmORz0dyFzrXM5YcRlAQDJtPoPmqSjGTPxSuQKsrRRn7PUuRBMArIk9XBErk3ZvcUhYecR6SLulDUI09veY4KbJ4xG/czokP9VbQ96cAzILhNn/lHFFqhg7hkt8PSW3GlUuOkIBt8TFh0MjVPfx0vi0B7DTDFR3Dyvxi0psCFKPNLl4G5IQXIQ5vK5rErN/j5KIo1qSxPgMTT709sFLQ2lRejWDE3OlNn7+RQDlz4LAjnKqGVFST8NbRR/kl3FA4TZNmOeZpIEDlULjGIURW3iJZZne/zeLmoxUZWvDQD8Rn/TZeyiv8zrVMS7hM6rvcTYRUc+mUmVZioHvYl0tXd1lMtGEaMOJA0COvUP/+wEt/lBGCpLHL0vnyX0gPJ0Esf6yEM0CtIVfWU4YMQUM4KUdM+Ce74=
    on:
      branch: master
      tags: true
      distributions: sdist bdist_wheel
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
