# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gallochri/dev/glBooklet/glBooklet/resources/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(300, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 485))
        MainWindow.setMaximumSize(QtCore.QSize(300, 485))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.go_button = QtWidgets.QPushButton(self.centralwidget)
        self.go_button.setEnabled(False)
        self.go_button.setGeometry(QtCore.QRect(210, 190, 80, 27))
        self.go_button.setObjectName("go_button")
        self.progress_bar_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_bar_label.setGeometry(QtCore.QRect(10, 380, 63, 19))
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(10, 400, 281, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 60, 291, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.grid_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("grid_layout")
        self.input_file_label = QtWidgets.QLabel(self.layoutWidget)
        self.input_file_label.setObjectName("input_file_label")
        self.grid_layout.addWidget(self.input_file_label, 0, 0, 1, 1)
        self.selected_file = QtWidgets.QLineEdit(self.layoutWidget)
        self.selected_file.setObjectName("selected_file")
        self.grid_layout.addWidget(self.selected_file, 1, 0, 1, 1)
        self.select_file = QtWidgets.QPushButton(self.layoutWidget)
        self.select_file.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/images/document-import.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_file.setIcon(icon1)
        self.select_file.setObjectName("select_file")
        self.grid_layout.addWidget(self.select_file, 1, 1, 1, 1)
        self.output_dir_label = QtWidgets.QLabel(self.layoutWidget)
        self.output_dir_label.setObjectName("output_dir_label")
        self.grid_layout.addWidget(self.output_dir_label, 2, 0, 1, 1)
        self.selected_dir = QtWidgets.QLineEdit(self.layoutWidget)
        self.selected_dir.setEnabled(False)
        self.selected_dir.setObjectName("selected_dir")
        self.grid_layout.addWidget(self.selected_dir, 3, 0, 1, 1)
        self.select_dir = QtWidgets.QPushButton(self.layoutWidget)
        self.select_dir.setEnabled(False)
        self.select_dir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/images/document-export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_dir.setIcon(icon2)
        self.select_dir.setObjectName("select_dir")
        self.grid_layout.addWidget(self.select_dir, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 282, 38))
        self.label.setStyleSheet("font: 75 20pt \"Open Sans\";\n"
"image: url(:/resources/images/logo32x32.png);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 23))
        self.menubar.setStyleSheet(");")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/images/application-exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon3)
        self.action_exit.setObjectName("action_exit")
        self.action_manual = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/images/help-about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_manual.setIcon(icon4)
        self.action_manual.setObjectName("action_manual")
        self.action_donate = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/images/help-donate.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_donate.setIcon(icon5)
        self.action_donate.setObjectName("action_donate")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/images/QtIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon6)
        self.action_about.setObjectName("action_about")
        self.menuFile.addAction(self.action_exit)
        self.menuHelp.addAction(self.action_manual)
        self.menuHelp.addAction(self.action_donate)
        self.menuHelp.addAction(self.action_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "galloBooklet"))
        self.go_button.setText(_translate("MainWindow", "Go!"))
        self.progress_bar_label.setText(_translate("MainWindow", "Status:"))
        self.input_file_label.setText(_translate("MainWindow", "Input File:"))
        self.output_dir_label.setText(_translate("MainWindow", "Output Folder:"))
        self.label.setText(_translate("MainWindow", "glBooklet"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.action_exit.setText(_translate("MainWindow", "&Exit"))
        self.action_exit.setToolTip(_translate("MainWindow", "&Exit"))
        self.action_manual.setText(_translate("MainWindow", "&Manual"))
        self.action_donate.setText(_translate("MainWindow", "&Donate"))
        self.action_about.setText(_translate("MainWindow", "&About"))

from . import mainwindow_rc
