dist: trusty
sudo: true

os:
  - linux

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.yarn-cache

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - nightly

matrix:
  include:
  - env: WITH_YARN=yes
    python: "3.5"
  - env: CHECK_INSTALL=yes
    python: "3.5"

before_install:
  - pip --version
  - pip install codecov
  - pip install -U pip setuptools
  - GIT_LFS_VERSION=1.5.4
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      mkdir -p $HOME/bin
      wget https://github.com/github/git-lfs/releases/download/v$GIT_LFS_VERSION/git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
      tar xvfz git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz
      mv git-lfs-$GIT_LFS_VERSION/git-lfs $HOME/bin/git-lfs
      export PATH=$PATH:$HOME/bin/
    fi
  - |
    if [[ $WITH_YARN == 'yes' ]]; then
      # Repo for newer Node.js versions
      curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      # Repo for Yarn
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      sudo apt-get update -qq && sudo apt-get install -y -qq yarn
    fi

install:
  - pip install tox-travis

before_script:
  - git lfs version
  - git lfs pull

script:
  - |
    if [[ "$CHECK_INSTALL" == 'yes' ]]; then
      pip install .
      elm-doc --help
      python -c 'import os, elm_doc; assert elm_doc.elm_package_overlayer_env("", "", os.environ)["LD_PRELOAD"]'
    else
      tox -v
    fi

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
