version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:19
     steps:
        - checkout

        - run:
            name: Install
            command: |
                python setup.py develop

        - run:
            command:  |
                nosetests
            environment:
