---
- name: install the RPM with the pre-built overcloud images
  become: yes
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ install.images.url is defined | ternary(install.images.get('url', '').split(','), ['rhosp-director-images']) }}"

# todo(yfried): investigate gtar error "Warning: Cannot stat: No such file or directory")'
- name: untar the images
  become: yes
  unarchive:
      src: "/usr/share/rhosp-director-images/{{ item }}"
      dest: "~{{ install.user.name }}/"
      copy: no
      owner: "{{ install.user.name }}"
      group: "{{ install.user.name }}"
      list_files: yes
  register: image_files
  with_items: "{{ tar_images }}"
