stages:
  - test
  - upload
before_script:
  - apk add --update alpine-sdk

dev:tests:
  image: library/python:3.6.5-alpine3.7
  stage: test
  script:
    - python3 -m pip install tox
    - make test
  except:
    - master
    - tags
  artifacts:
    paths:
    - doc/tests.html
    - doc/coverage/

dev:upload:
  image: library/python:3.6.5-alpine3.7
  stage: upload
  only:
    - tags
  script:
    - make release

pages:
  image: library/python:3.6.5-alpine3.7
  stage: upload
  only:
    - master
  script:
    - make public
  artifacts:
    paths:
    - public    